/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2016-08-30 10:37:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.trampoline.scrapped;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Enumeration;
import com.monumental.trampoline.component.*;
import com.monumental.trampoline.security.*;
import com.reeltrack.reels.*;
import com.reeltrack.users.*;
import com.reeltrack.whlocations.*;
import com.reeltrack.drivers.*;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(32);
    _jspx_dependants.put("/WEB-INF/tags/form/row_begin.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/admin/subtitle.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/select_end.tag", Long.valueOf(1472002170000L));
    _jspx_dependants.put("/WEB-INF/tags/form/submit_inline.tag", Long.valueOf(1472425523000L));
    _jspx_dependants.put("/WEB-INF/tags/admin/title.tag", Long.valueOf(1472493852000L));
    _jspx_dependants.put("/WEB-INF/tags/admin/set_tabset.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/info.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/textfield.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/admin/box_end.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/buttonset_end.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/hidden.tag", Long.valueOf(1472002170000L));
    _jspx_dependants.put("/WEB-INF/tags/html/end.tag", Long.valueOf(1472002193000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1472002170000L));
    _jspx_dependants.put("/WEB-INF/tags/admin/box_begin.tag", Long.valueOf(1472498302000L));
    _jspx_dependants.put("/WEB-INF/tags/form/select_begin.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/linkbutton.tag", Long.valueOf(1472521293000L));
    _jspx_dependants.put("/WEB-INF/tags/form/content_begin.tag", Long.valueOf(1472496815000L));
    _jspx_dependants.put("/WEB-INF/tags/form/content_end.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/option.tag", Long.valueOf(1472002170000L));
    _jspx_dependants.put("/WEB-INF/tags/form/begin.tag", Long.valueOf(1472529757000L));
    _jspx_dependants.put("/trampoline/scrapped/../common/includes/only_users.jsp", Long.valueOf(1472002170000L));
    _jspx_dependants.put("jar:file:/www/new/tomcat/webapps/../../web/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098725490000L));
    _jspx_dependants.put("/WEB-INF/tags/html/begin.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/begin_selfsubmit.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/label.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("jar:file:/www/new/tomcat/webapps/../../web/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098725490000L));
    _jspx_dependants.put("/WEB-INF/tags/form/end.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/label_inline.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/end_inline.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/row_end.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/begin_selfsubmit_inline.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/buttonset_begin.tag", Long.valueOf(1472002192000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\n");
      com.reeltrack.users.RTUserLoginMgr onlyuserLoginMgr = null;
      onlyuserLoginMgr = (com.reeltrack.users.RTUserLoginMgr) _jspx_page_context.getAttribute("onlyuserLoginMgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (onlyuserLoginMgr == null){
        onlyuserLoginMgr = new com.reeltrack.users.RTUserLoginMgr();
        _jspx_page_context.setAttribute("onlyuserLoginMgr", onlyuserLoginMgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
      out.write('\n');
 onlyuserLoginMgr.init(pageContext); 
      out.write('\n');
      out.write('\n');
 if(!onlyuserLoginMgr.isLoggedIn()) { 
      out.write("\n");
      out.write("\t<script type=\"text/javascript\" language=\"javascript\">\n");
      out.write("\t\t\t// first, if we're in the _submissionFrame, call window location on the parent\n");
      out.write("\t\t\tparent.window.location = \"");
      out.print( request.getContextPath() );
      out.write("/trampoline/index.jsp\";\n");
      out.write("\t\n");
      out.write("\t\t\t// otherwise, we'll be doing this on this window\n");
      out.write("\t\t\twindow.location = \"");
      out.print( request.getContextPath() );
      out.write("/trampoline/index.jsp\";\n");
      out.write("\t</script>\n");
 } 
      out.write('\n');
 if(!onlyuserLoginMgr.isLoggedIn()) return; 
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      com.monumental.trampoline.datasources.DbResources dbResources = null;
      dbResources = (com.monumental.trampoline.datasources.DbResources) _jspx_page_context.getAttribute("dbResources", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (dbResources == null){
        dbResources = new com.monumental.trampoline.datasources.DbResources();
        _jspx_page_context.setAttribute("dbResources", dbResources, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
      com.reeltrack.users.RTUserLoginMgr userLoginMgr = null;
      userLoginMgr = (com.reeltrack.users.RTUserLoginMgr) _jspx_page_context.getAttribute("userLoginMgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (userLoginMgr == null){
        userLoginMgr = new com.reeltrack.users.RTUserLoginMgr();
        _jspx_page_context.setAttribute("userLoginMgr", userLoginMgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
      com.reeltrack.whlocations.WhLocationMgr locationMgr = null;
      locationMgr = (com.reeltrack.whlocations.WhLocationMgr) _jspx_page_context.getAttribute("locationMgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (locationMgr == null){
        locationMgr = new com.reeltrack.whlocations.WhLocationMgr();
        _jspx_page_context.setAttribute("locationMgr", locationMgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
      com.reeltrack.reels.ReelMgr reelMgr = null;
      reelMgr = (com.reeltrack.reels.ReelMgr) _jspx_page_context.getAttribute("reelMgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (reelMgr == null){
        reelMgr = new com.reeltrack.reels.ReelMgr();
        _jspx_page_context.setAttribute("reelMgr", reelMgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
      com.reeltrack.drivers.DriverMgr driverMgr = null;
      driverMgr = (com.reeltrack.drivers.DriverMgr) _jspx_page_context.getAttribute("driverMgr", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (driverMgr == null){
        driverMgr = new com.reeltrack.drivers.DriverMgr();
        _jspx_page_context.setAttribute("driverMgr", driverMgr, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');
 userLoginMgr.init(pageContext); 
      out.write('\n');
 reelMgr.init(pageContext,dbResources); 
      out.write('\n');
 locationMgr.init(pageContext,dbResources); 
      out.write('\n');
 driverMgr.init(pageContext,dbResources); 
      out.write('\n');

RTUser user = (RTUser)userLoginMgr.getUser();

int howMany = 25;
int pageNum = 1;
if(request.getParameter("pageNum") != null) {
    pageNum = Integer.parseInt(request.getParameter("pageNum"));
    session.setAttribute("shipping/search.jsp", pageNum);
} else {
    if(session.getAttribute("shipping/search.jsp") != null) {
        pageNum = (Integer)session.getAttribute("shipping/search.jsp");
    }
}

int skip = (pageNum-1) * howMany;

if(request.getParameter("skip") != null) {
    skip = Integer.parseInt(request.getParameter("skip"));
}

Reel content = new Reel();
if(session.getAttribute("scrapped_search")!=null) {
    content = (Reel)session.getAttribute("scrapped_search");
}

content.setStatus(Reel.STATUS_COMPLETE);

if(request.getParameter(Reel.REEL_TAG_COLUMN) != null) {
    content.setReelTag(request.getParameter(Reel.REEL_TAG_COLUMN));
    content.setSearchOp(Reel.REEL_TAG_COLUMN, Reel.TRUE_PARTIAL);
}

if(request.getParameter(Reel.CABLE_DESCRIPTION_COLUMN) != null) {
    content.setCableDescription(request.getParameter(Reel.CABLE_DESCRIPTION_COLUMN));
    content.setSearchOp(Reel.CABLE_DESCRIPTION_COLUMN, Reel.TRUE_PARTIAL);
}

if(request.getParameter(Reel.CUSTOMER_PN_COLUMN) != null) {
    content.setCustomerPN(request.getParameter(Reel.CUSTOMER_PN_COLUMN));
    content.setSearchOp(Reel.CUSTOMER_PN_COLUMN, Reel.PARTIAL);
}

if(request.getParameter(Reel.MANUFACTURER_COLUMN) != null) {
    content.setManufacturer(request.getParameter(Reel.MANUFACTURER_COLUMN));
    content.setSearchOp(Reel.MANUFACTURER_COLUMN, Reel.EQ);
}

if(request.getParameter(Reel.CR_ID_COLUMN) != null) {
    if(request.getParameter(Reel.CR_ID_COLUMN).equals("")) {
        content.getData().removeValue(Reel.CR_ID_COLUMN);
    } else {
        content.setCrId(Integer.parseInt(request.getParameter(Reel.CR_ID_COLUMN)));
        content.setSearchOp(Reel.CR_ID_COLUMN, Reel.EQ);
    }
}

session.setAttribute("scrapped_search",content);

String column = Reel.REEL_TAG_COLUMN;
boolean ascending = true;
int count = reelMgr.searchReelsCount(content, column, ascending);
int pages = (int)Math.ceil((double)count / howMany);
CompEntities contents = reelMgr.searchReels(content, column, ascending, howMany, skip);
String[] manufacturers = reelMgr.getManufacturers();

boolean dosearch = true;
String tempURL = "";

      out.write('\n');
      out.write('\n');
 dbResources.close(); 
      out.write('\n');
      if (_jspx_meth_html_005fbegin_005f0(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_admin_005ftitle_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_admin_005fsubtitle_005f0(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_admin_005fbox_005fbegin_005f0(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_form_005fbegin_005fselfsubmit_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
 if(content.getCrId()!=0) { 
      out.write('\n');
      out.write('	');
      out.write('	');
      //  form:textfield
      org.apache.jsp.tag.webform.textfield_tag _jspx_th_form_005ftextfield_005f0 = (new org.apache.jsp.tag.webform.textfield_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005ftextfield_005f0);
      _jspx_th_form_005ftextfield_005f0.setJspContext(_jspx_page_context);
      // /trampoline/scrapped/search.jsp(106,2) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f0.setLabel("CRID #:");
      // /trampoline/scrapped/search.jsp(106,2) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f0.setName( Reel.CR_ID_COLUMN );
      // /trampoline/scrapped/search.jsp(106,2) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f0.setValue( new Integer(content.getCrId()).toString() );
      _jspx_th_form_005ftextfield_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005ftextfield_005f0);
      out.write('\n');
      out.write('	');
 } else { 
      out.write('\n');
      out.write('	');
      out.write('	');
      //  form:textfield
      org.apache.jsp.tag.webform.textfield_tag _jspx_th_form_005ftextfield_005f1 = (new org.apache.jsp.tag.webform.textfield_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005ftextfield_005f1);
      _jspx_th_form_005ftextfield_005f1.setJspContext(_jspx_page_context);
      // /trampoline/scrapped/search.jsp(108,2) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f1.setLabel("CRID #:");
      // /trampoline/scrapped/search.jsp(108,2) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f1.setName( Reel.CR_ID_COLUMN );
      // /trampoline/scrapped/search.jsp(108,2) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f1.setValue("");
      _jspx_th_form_005ftextfield_005f1.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005ftextfield_005f1);
      out.write('\n');
      out.write('	');
 } 
      out.write('\n');
      out.write('	');
      //  form:textfield
      org.apache.jsp.tag.webform.textfield_tag _jspx_th_form_005ftextfield_005f2 = (new org.apache.jsp.tag.webform.textfield_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005ftextfield_005f2);
      _jspx_th_form_005ftextfield_005f2.setJspContext(_jspx_page_context);
      // /trampoline/scrapped/search.jsp(110,1) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f2.setLabel("Reel Tag:");
      // /trampoline/scrapped/search.jsp(110,1) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f2.setName( Reel.REEL_TAG_COLUMN );
      // /trampoline/scrapped/search.jsp(110,1) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f2.setValue( content.getReelTag() );
      _jspx_th_form_005ftextfield_005f2.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005ftextfield_005f2);
      out.write("\n");
      out.write("    ");
      //  form:textfield
      org.apache.jsp.tag.webform.textfield_tag _jspx_th_form_005ftextfield_005f3 = (new org.apache.jsp.tag.webform.textfield_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005ftextfield_005f3);
      _jspx_th_form_005ftextfield_005f3.setJspContext(_jspx_page_context);
      // /trampoline/scrapped/search.jsp(111,4) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f3.setLabel("Description:");
      // /trampoline/scrapped/search.jsp(111,4) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f3.setName( Reel.CABLE_DESCRIPTION_COLUMN );
      // /trampoline/scrapped/search.jsp(111,4) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f3.setValue( content.getCableDescription() );
      _jspx_th_form_005ftextfield_005f3.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005ftextfield_005f3);
      out.write("\n");
      out.write("    ");
 tempURL = user.getCustomerName() + " P/N:"; 
      out.write("\n");
      out.write("    ");
      //  form:textfield
      org.apache.jsp.tag.webform.textfield_tag _jspx_th_form_005ftextfield_005f4 = (new org.apache.jsp.tag.webform.textfield_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005ftextfield_005f4);
      _jspx_th_form_005ftextfield_005f4.setJspContext(_jspx_page_context);
      // /trampoline/scrapped/search.jsp(113,4) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f4.setLabel( tempURL );
      // /trampoline/scrapped/search.jsp(113,4) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f4.setName( Reel.CUSTOMER_PN_COLUMN );
      // /trampoline/scrapped/search.jsp(113,4) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f4.setValue( content.getCustomerPN() );
      _jspx_th_form_005ftextfield_005f4.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005ftextfield_005f4);
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_form_005frow_005fbegin_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_form_005flabel_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_form_005fcontent_005fbegin_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
      //  form:select_begin
      org.apache.jsp.tag.webform.select_005fbegin_tag _jspx_th_form_005fselect_005fbegin_005f0 = (new org.apache.jsp.tag.webform.select_005fbegin_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005fselect_005fbegin_005f0);
      _jspx_th_form_005fselect_005fbegin_005f0.setJspContext(_jspx_page_context);
      // /trampoline/scrapped/search.jsp(117,8) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fselect_005fbegin_005f0.setName( Reel.MANUFACTURER_COLUMN );
      _jspx_th_form_005fselect_005fbegin_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005fselect_005fbegin_005f0);
      out.write("\n");
      out.write("            ");
      //  form:option
      org.apache.jsp.tag.webform.option_tag _jspx_th_form_005foption_005f0 = (new org.apache.jsp.tag.webform.option_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005foption_005f0);
      _jspx_th_form_005foption_005f0.setJspContext(_jspx_page_context);
      // /trampoline/scrapped/search.jsp(118,12) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005foption_005f0.setName("Any");
      // /trampoline/scrapped/search.jsp(118,12) name = value type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005foption_005f0.setValue("");
      // /trampoline/scrapped/search.jsp(118,12) name = match type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005foption_005f0.setMatch( content.getManufacturer() );
      _jspx_th_form_005foption_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005foption_005f0);
      out.write("\n");
      out.write("            ");
 for(int x=0; x<manufacturers.length; x++) { 
      out.write("\n");
      out.write("                ");
      //  form:option
      org.apache.jsp.tag.webform.option_tag _jspx_th_form_005foption_005f1 = (new org.apache.jsp.tag.webform.option_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005foption_005f1);
      _jspx_th_form_005foption_005f1.setJspContext(_jspx_page_context);
      // /trampoline/scrapped/search.jsp(120,16) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005foption_005f1.setName( manufacturers[x] );
      // /trampoline/scrapped/search.jsp(120,16) name = value type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005foption_005f1.setValue( manufacturers[x] );
      // /trampoline/scrapped/search.jsp(120,16) name = match type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005foption_005f1.setMatch( content.getManufacturer() );
      _jspx_th_form_005foption_005f1.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005foption_005f1);
      out.write("\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_form_005fselect_005fend_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_form_005fcontent_005fend_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_form_005frow_005fend_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_form_005frow_005fbegin_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_form_005flabel_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_form_005fbuttonset_005fbegin_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_form_005fsubmit_005finline_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_form_005fbuttonset_005fend_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_form_005frow_005fend_005f1(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_form_005fend_005f0(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_admin_005fbox_005fend_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('\n');
 if(dosearch) { 
      out.write('\n');
 if(contents.howMany() > 0) { 
      out.write('\n');
      //  admin:box_begin
      org.apache.jsp.tag.webadmin.box_005fbegin_tag _jspx_th_admin_005fbox_005fbegin_005f1 = (new org.apache.jsp.tag.webadmin.box_005fbegin_tag());
      _jsp_instancemanager.newInstance(_jspx_th_admin_005fbox_005fbegin_005f1);
      _jspx_th_admin_005fbox_005fbegin_005f1.setJspContext(_jspx_page_context);
      // /trampoline/scrapped/search.jsp(136,0) name = color type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_admin_005fbox_005fbegin_005f1.setColor("silver");
      // /trampoline/scrapped/search.jsp(136,0) name = text type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_admin_005fbox_005fbegin_005f1.setText("Reels");
      // /trampoline/scrapped/search.jsp(136,0) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_admin_005fbox_005fbegin_005f1.setName("results");
      // /trampoline/scrapped/search.jsp(136,0) name = url type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_admin_005fbox_005fbegin_005f1.setUrl("scrapped/search.jsp");
      // /trampoline/scrapped/search.jsp(136,0) name = pages type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_admin_005fbox_005fbegin_005f1.setPages( Integer.toString(pages) );
      // /trampoline/scrapped/search.jsp(136,0) name = pageNum type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_admin_005fbox_005fbegin_005f1.setPageNum( Integer.toString(pageNum) );
      _jspx_th_admin_005fbox_005fbegin_005f1.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fbox_005fbegin_005f1);
      out.write('\n');
      if (_jspx_meth_admin_005fbox_005fend_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
 for(int i=0; i<contents.howMany(); i++) { 
      out.write("\n");
      out.write("        ");
 content = (Reel)contents.get(i); 
      out.write("\n");
      out.write("        ");
 tempURL = new Integer(i+1).toString() + ". " + content.getReelTag() + " (" + content.getCableDescription() + ")"; 
      out.write("\n");
      out.write("        ");
 String toggleTarget = "toggleReelrec" + content.getId(); 
      out.write("\n");
      out.write("        ");
 String toggleID = "reelrec" + content.getId(); 
      out.write("\n");
      out.write("        ");
 String toggleForm = "reelFormrec" + content.getId(); 
      out.write("\n");
      out.write("\n");
      out.write("        ");

        String reelName = content.getCrId() + " : " + content.getReelTag() + " : " + content.getCableDescription();
        String reelId = "reel" + content.getCrId();
        
      out.write("\n");
      out.write("        ");
      //  admin:box_begin
      org.apache.jsp.tag.webadmin.box_005fbegin_tag _jspx_th_admin_005fbox_005fbegin_005f2 = (new org.apache.jsp.tag.webadmin.box_005fbegin_tag());
      _jsp_instancemanager.newInstance(_jspx_th_admin_005fbox_005fbegin_005f2);
      _jspx_th_admin_005fbox_005fbegin_005f2.setJspContext(_jspx_page_context);
      // /trampoline/scrapped/search.jsp(149,8) name = open type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_admin_005fbox_005fbegin_005f2.setOpen("false");
      // /trampoline/scrapped/search.jsp(149,8) name = text type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_admin_005fbox_005fbegin_005f2.setText( reelName );
      // /trampoline/scrapped/search.jsp(149,8) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_admin_005fbox_005fbegin_005f2.setName( reelId );
      _jspx_th_admin_005fbox_005fbegin_005f2.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fbox_005fbegin_005f2);
      out.write("\n");
      out.write("            ");
      //  form:begin
      org.apache.jsp.tag.webform.begin_tag _jspx_th_form_005fbegin_005f0 = (new org.apache.jsp.tag.webform.begin_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005fbegin_005f0);
      _jspx_th_form_005fbegin_005f0.setJspContext(_jspx_page_context);
      // /trampoline/scrapped/search.jsp(150,12) name = submit type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fbegin_005f0.setSubmit("true");
      // /trampoline/scrapped/search.jsp(150,12) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fbegin_005f0.setName( toggleForm );
      // /trampoline/scrapped/search.jsp(150,12) name = action type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fbegin_005f0.setAction("scrapped/process.jsp");
      _jspx_th_form_005fbegin_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005fbegin_005f0);
      out.write("\n");
      out.write("                ");
      //  form:info
      org.apache.jsp.tag.webform.info_tag _jspx_th_form_005finfo_005f0 = (new org.apache.jsp.tag.webform.info_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005finfo_005f0);
      _jspx_th_form_005finfo_005f0.setJspContext(_jspx_page_context);
      // /trampoline/scrapped/search.jsp(151,16) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f0.setLabel("Reel Tag:");
      // /trampoline/scrapped/search.jsp(151,16) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f0.setText( content.getReelTag() );
      _jspx_th_form_005finfo_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005finfo_005f0);
      out.write("\n");
      out.write("                ");
      //  form:info
      org.apache.jsp.tag.webform.info_tag _jspx_th_form_005finfo_005f1 = (new org.apache.jsp.tag.webform.info_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005finfo_005f1);
      _jspx_th_form_005finfo_005f1.setJspContext(_jspx_page_context);
      // /trampoline/scrapped/search.jsp(152,16) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f1.setLabel("Cable Description:");
      // /trampoline/scrapped/search.jsp(152,16) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f1.setText( content.getCableDescription() );
      _jspx_th_form_005finfo_005f1.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005finfo_005f1);
      out.write("\n");
      out.write("                ");
      //  form:info
      org.apache.jsp.tag.webform.info_tag _jspx_th_form_005finfo_005f2 = (new org.apache.jsp.tag.webform.info_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005finfo_005f2);
      _jspx_th_form_005finfo_005f2.setJspContext(_jspx_page_context);
      // /trampoline/scrapped/search.jsp(153,16) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f2.setLabel("Customer P/N:");
      // /trampoline/scrapped/search.jsp(153,16) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f2.setText( content.getCustomerPN() );
      _jspx_th_form_005finfo_005f2.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005finfo_005f2);
      out.write("\n");
      out.write("                ");
      //  form:info
      org.apache.jsp.tag.webform.info_tag _jspx_th_form_005finfo_005f3 = (new org.apache.jsp.tag.webform.info_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005finfo_005f3);
      _jspx_th_form_005finfo_005f3.setJspContext(_jspx_page_context);
      // /trampoline/scrapped/search.jsp(154,16) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f3.setLabel("Manufacturer:");
      // /trampoline/scrapped/search.jsp(154,16) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f3.setText( content.getManufacturer() );
      _jspx_th_form_005finfo_005f3.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005finfo_005f3);
      out.write("\n");
      out.write("                ");
      //  form:info
      org.apache.jsp.tag.webform.info_tag _jspx_th_form_005finfo_005f4 = (new org.apache.jsp.tag.webform.info_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005finfo_005f4);
      _jspx_th_form_005finfo_005f4.setJspContext(_jspx_page_context);
      // /trampoline/scrapped/search.jsp(155,16) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f4.setLabel("Reel Type:");
      // /trampoline/scrapped/search.jsp(155,16) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f4.setText( content.getReelType() );
      _jspx_th_form_005finfo_005f4.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005finfo_005f4);
      out.write("\n");
      out.write("                ");
      //  form:info
      org.apache.jsp.tag.webform.info_tag _jspx_th_form_005finfo_005f5 = (new org.apache.jsp.tag.webform.info_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005finfo_005f5);
      _jspx_th_form_005finfo_005f5.setJspContext(_jspx_page_context);
      // /trampoline/scrapped/search.jsp(156,16) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f5.setLabel("Received Qty:");
      // /trampoline/scrapped/search.jsp(156,16) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f5.setText( new Integer(content.getReceivedQuantity()).toString() );
      _jspx_th_form_005finfo_005f5.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005finfo_005f5);
      out.write("\n");
      out.write("                ");
      //  form:info
      org.apache.jsp.tag.webform.info_tag _jspx_th_form_005finfo_005f6 = (new org.apache.jsp.tag.webform.info_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005finfo_005f6);
      _jspx_th_form_005finfo_005f6.setJspContext(_jspx_page_context);
      // /trampoline/scrapped/search.jsp(157,16) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f6.setLabel("Current Qty:");
      // /trampoline/scrapped/search.jsp(157,16) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f6.setText( new Integer(content.getOnReelQuantity()).toString() );
      _jspx_th_form_005finfo_005f6.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005finfo_005f6);
      out.write("\n");
      out.write("                ");
      if (_jspx_meth_form_005finfo_005f7(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                ");
      //  form:info
      org.apache.jsp.tag.webform.info_tag _jspx_th_form_005finfo_005f8 = (new org.apache.jsp.tag.webform.info_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005finfo_005f8);
      _jspx_th_form_005finfo_005f8.setJspContext(_jspx_page_context);
      // /trampoline/scrapped/search.jsp(159,16) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f8.setLabel("Warehouse<br />Location:");
      // /trampoline/scrapped/search.jsp(159,16) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f8.setText( content.getWharehouseLocation() );
      _jspx_th_form_005finfo_005f8.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005finfo_005f8);
      out.write("\n");
      out.write("                ");
      //  form:hidden
      org.apache.jsp.tag.webform.hidden_tag _jspx_th_form_005fhidden_005f0 = (new org.apache.jsp.tag.webform.hidden_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005fhidden_005f0);
      _jspx_th_form_005fhidden_005f0.setJspContext(_jspx_page_context);
      // /trampoline/scrapped/search.jsp(160,16) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fhidden_005f0.setName( Reel.PARAM );
      // /trampoline/scrapped/search.jsp(160,16) name = value type = java.lang.Object reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fhidden_005f0.setValue( new Integer(content.getId()).toString() );
      _jspx_th_form_005fhidden_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005fhidden_005f0);
      out.write("\n");
      out.write("                ");
      if (_jspx_meth_form_005frow_005fbegin_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                ");
      if (_jspx_meth_form_005flabel_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                ");
      if (_jspx_meth_form_005fbuttonset_005fbegin_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                    ");
      if (_jspx_meth_form_005fsubmit_005finline_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                    ");
 tempURL = "reels/edit.jsp?" +  Reel.PARAM + "=" + content.getId(); 
      out.write("\n");
      out.write("                    ");
      //  form:linkbutton
      org.apache.jsp.tag.webform.linkbutton_tag _jspx_th_form_005flinkbutton_005f0 = (new org.apache.jsp.tag.webform.linkbutton_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005flinkbutton_005f0);
      _jspx_th_form_005flinkbutton_005f0.setJspContext(_jspx_page_context);
      // /trampoline/scrapped/search.jsp(166,20) name = url type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005flinkbutton_005f0.setUrl( tempURL );
      // /trampoline/scrapped/search.jsp(166,20) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005flinkbutton_005f0.setName("EDIT REEL");
      _jspx_th_form_005flinkbutton_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005flinkbutton_005f0);
      out.write("\n");
      out.write("                ");
      if (_jspx_meth_form_005fbuttonset_005fend_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                ");
      if (_jspx_meth_form_005frow_005fend_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_form_005fend_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_admin_005fbox_005fend_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("    ");
 } 
      out.write('\n');
 } else { 
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_admin_005fsubtitle_005f1(_jspx_page_context))
        return;
      out.write('\n');
 } 
      out.write('\n');
 } 
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_admin_005fset_005ftabset_005f0(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_html_005fend_005f0(_jspx_page_context))
        return;
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_html_005fbegin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:begin
    org.apache.jsp.tag.webhtml.begin_tag _jspx_th_html_005fbegin_005f0 = (new org.apache.jsp.tag.webhtml.begin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_html_005fbegin_005f0);
    _jspx_th_html_005fbegin_005f0.setJspContext(_jspx_page_context);
    _jspx_th_html_005fbegin_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_html_005fbegin_005f0);
    return false;
  }

  private boolean _jspx_meth_admin_005ftitle_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:title
    org.apache.jsp.tag.webadmin.title_tag _jspx_th_admin_005ftitle_005f0 = (new org.apache.jsp.tag.webadmin.title_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005ftitle_005f0);
    _jspx_th_admin_005ftitle_005f0.setJspContext(_jspx_page_context);
    // /trampoline/scrapped/search.jsp(100,0) name = heading type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005ftitle_005f0.setHeading("Reels");
    // /trampoline/scrapped/search.jsp(100,0) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005ftitle_005f0.setText("Mark as Scrapped");
    _jspx_th_admin_005ftitle_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005ftitle_005f0);
    return false;
  }

  private boolean _jspx_meth_admin_005fsubtitle_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:subtitle
    org.apache.jsp.tag.webadmin.subtitle_tag _jspx_th_admin_005fsubtitle_005f0 = (new org.apache.jsp.tag.webadmin.subtitle_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fsubtitle_005f0);
    _jspx_th_admin_005fsubtitle_005f0.setJspContext(_jspx_page_context);
    // /trampoline/scrapped/search.jsp(102,0) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fsubtitle_005f0.setText("Filter Reels");
    _jspx_th_admin_005fsubtitle_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fsubtitle_005f0);
    return false;
  }

  private boolean _jspx_meth_admin_005fbox_005fbegin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:box_begin
    org.apache.jsp.tag.webadmin.box_005fbegin_tag _jspx_th_admin_005fbox_005fbegin_005f0 = (new org.apache.jsp.tag.webadmin.box_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fbox_005fbegin_005f0);
    _jspx_th_admin_005fbox_005fbegin_005f0.setJspContext(_jspx_page_context);
    // /trampoline/scrapped/search.jsp(103,0) name = text type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fbox_005fbegin_005f0.setText("Filter Reels");
    // /trampoline/scrapped/search.jsp(103,0) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fbox_005fbegin_005f0.setName("Filter_Reels");
    // /trampoline/scrapped/search.jsp(103,0) name = open type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fbox_005fbegin_005f0.setOpen("false");
    _jspx_th_admin_005fbox_005fbegin_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fbox_005fbegin_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005fbegin_005fselfsubmit_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:begin_selfsubmit
    org.apache.jsp.tag.webform.begin_005fselfsubmit_tag _jspx_th_form_005fbegin_005fselfsubmit_005f0 = (new org.apache.jsp.tag.webform.begin_005fselfsubmit_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fbegin_005fselfsubmit_005f0);
    _jspx_th_form_005fbegin_005fselfsubmit_005f0.setJspContext(_jspx_page_context);
    // /trampoline/scrapped/search.jsp(104,0) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fbegin_005fselfsubmit_005f0.setName("search");
    // /trampoline/scrapped/search.jsp(104,0) name = action type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fbegin_005fselfsubmit_005f0.setAction("scrapped/search.jsp");
    _jspx_th_form_005fbegin_005fselfsubmit_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fbegin_005fselfsubmit_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005frow_005fbegin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:row_begin
    org.apache.jsp.tag.webform.row_005fbegin_tag _jspx_th_form_005frow_005fbegin_005f0 = (new org.apache.jsp.tag.webform.row_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005frow_005fbegin_005f0);
    _jspx_th_form_005frow_005fbegin_005f0.setJspContext(_jspx_page_context);
    _jspx_th_form_005frow_005fbegin_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005frow_005fbegin_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005flabel_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:label
    org.apache.jsp.tag.webform.label_tag _jspx_th_form_005flabel_005f0 = (new org.apache.jsp.tag.webform.label_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005flabel_005f0);
    _jspx_th_form_005flabel_005f0.setJspContext(_jspx_page_context);
    // /trampoline/scrapped/search.jsp(115,8) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005flabel_005f0.setName("");
    // /trampoline/scrapped/search.jsp(115,8) name = label type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005flabel_005f0.setLabel("Manufacturer:");
    _jspx_th_form_005flabel_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005flabel_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005fcontent_005fbegin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:content_begin
    org.apache.jsp.tag.webform.content_005fbegin_tag _jspx_th_form_005fcontent_005fbegin_005f0 = (new org.apache.jsp.tag.webform.content_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fcontent_005fbegin_005f0);
    _jspx_th_form_005fcontent_005fbegin_005f0.setJspContext(_jspx_page_context);
    _jspx_th_form_005fcontent_005fbegin_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fcontent_005fbegin_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005fselect_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:select_end
    org.apache.jsp.tag.webform.select_005fend_tag _jspx_th_form_005fselect_005fend_005f0 = (new org.apache.jsp.tag.webform.select_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fselect_005fend_005f0);
    _jspx_th_form_005fselect_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_form_005fselect_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fselect_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005fcontent_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:content_end
    org.apache.jsp.tag.webform.content_005fend_tag _jspx_th_form_005fcontent_005fend_005f0 = (new org.apache.jsp.tag.webform.content_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fcontent_005fend_005f0);
    _jspx_th_form_005fcontent_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_form_005fcontent_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fcontent_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005frow_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:row_end
    org.apache.jsp.tag.webform.row_005fend_tag _jspx_th_form_005frow_005fend_005f0 = (new org.apache.jsp.tag.webform.row_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005frow_005fend_005f0);
    _jspx_th_form_005frow_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_form_005frow_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005frow_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005frow_005fbegin_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:row_begin
    org.apache.jsp.tag.webform.row_005fbegin_tag _jspx_th_form_005frow_005fbegin_005f1 = (new org.apache.jsp.tag.webform.row_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005frow_005fbegin_005f1);
    _jspx_th_form_005frow_005fbegin_005f1.setJspContext(_jspx_page_context);
    _jspx_th_form_005frow_005fbegin_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005frow_005fbegin_005f1);
    return false;
  }

  private boolean _jspx_meth_form_005flabel_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:label
    org.apache.jsp.tag.webform.label_tag _jspx_th_form_005flabel_005f1 = (new org.apache.jsp.tag.webform.label_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005flabel_005f1);
    _jspx_th_form_005flabel_005f1.setJspContext(_jspx_page_context);
    // /trampoline/scrapped/search.jsp(126,8) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005flabel_005f1.setName("");
    // /trampoline/scrapped/search.jsp(126,8) name = label type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005flabel_005f1.setLabel("");
    _jspx_th_form_005flabel_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005flabel_005f1);
    return false;
  }

  private boolean _jspx_meth_form_005fbuttonset_005fbegin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:buttonset_begin
    org.apache.jsp.tag.webform.buttonset_005fbegin_tag _jspx_th_form_005fbuttonset_005fbegin_005f0 = (new org.apache.jsp.tag.webform.buttonset_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fbuttonset_005fbegin_005f0);
    _jspx_th_form_005fbuttonset_005fbegin_005f0.setJspContext(_jspx_page_context);
    // /trampoline/scrapped/search.jsp(127,8) name = align type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fbuttonset_005fbegin_005f0.setAlign("left");
    // /trampoline/scrapped/search.jsp(127,8) name = padding type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fbuttonset_005fbegin_005f0.setPadding("0");
    _jspx_th_form_005fbuttonset_005fbegin_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fbuttonset_005fbegin_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005fsubmit_005finline_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:submit_inline
    org.apache.jsp.tag.webform.submit_005finline_tag _jspx_th_form_005fsubmit_005finline_005f0 = (new org.apache.jsp.tag.webform.submit_005finline_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fsubmit_005finline_005f0);
    _jspx_th_form_005fsubmit_005finline_005f0.setJspContext(_jspx_page_context);
    // /trampoline/scrapped/search.jsp(128,12) name = button type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f0.setButton("submit");
    // /trampoline/scrapped/search.jsp(128,12) name = waiting type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f0.setWaiting("true");
    // /trampoline/scrapped/search.jsp(128,12) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f0.setName("search");
    // /trampoline/scrapped/search.jsp(128,12) name = action type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f0.setAction("test");
    _jspx_th_form_005fsubmit_005finline_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fsubmit_005finline_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005fbuttonset_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:buttonset_end
    org.apache.jsp.tag.webform.buttonset_005fend_tag _jspx_th_form_005fbuttonset_005fend_005f0 = (new org.apache.jsp.tag.webform.buttonset_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fbuttonset_005fend_005f0);
    _jspx_th_form_005fbuttonset_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_form_005fbuttonset_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fbuttonset_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005frow_005fend_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:row_end
    org.apache.jsp.tag.webform.row_005fend_tag _jspx_th_form_005frow_005fend_005f1 = (new org.apache.jsp.tag.webform.row_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005frow_005fend_005f1);
    _jspx_th_form_005frow_005fend_005f1.setJspContext(_jspx_page_context);
    _jspx_th_form_005frow_005fend_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005frow_005fend_005f1);
    return false;
  }

  private boolean _jspx_meth_form_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:end
    org.apache.jsp.tag.webform.end_tag _jspx_th_form_005fend_005f0 = (new org.apache.jsp.tag.webform.end_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fend_005f0);
    _jspx_th_form_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_form_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_admin_005fbox_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:box_end
    org.apache.jsp.tag.webadmin.box_005fend_tag _jspx_th_admin_005fbox_005fend_005f0 = (new org.apache.jsp.tag.webadmin.box_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fbox_005fend_005f0);
    _jspx_th_admin_005fbox_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_admin_005fbox_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fbox_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_admin_005fbox_005fend_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:box_end
    org.apache.jsp.tag.webadmin.box_005fend_tag _jspx_th_admin_005fbox_005fend_005f1 = (new org.apache.jsp.tag.webadmin.box_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fbox_005fend_005f1);
    _jspx_th_admin_005fbox_005fend_005f1.setJspContext(_jspx_page_context);
    _jspx_th_admin_005fbox_005fend_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fbox_005fend_005f1);
    return false;
  }

  private boolean _jspx_meth_form_005finfo_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:info
    org.apache.jsp.tag.webform.info_tag _jspx_th_form_005finfo_005f7 = (new org.apache.jsp.tag.webform.info_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005finfo_005f7);
    _jspx_th_form_005finfo_005f7.setJspContext(_jspx_page_context);
    // /trampoline/scrapped/search.jsp(158,16) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005finfo_005f7.setLabel("Copper Weight:");
    // /trampoline/scrapped/search.jsp(158,16) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005finfo_005f7.setText("");
    _jspx_th_form_005finfo_005f7.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005finfo_005f7);
    return false;
  }

  private boolean _jspx_meth_form_005frow_005fbegin_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:row_begin
    org.apache.jsp.tag.webform.row_005fbegin_tag _jspx_th_form_005frow_005fbegin_005f2 = (new org.apache.jsp.tag.webform.row_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005frow_005fbegin_005f2);
    _jspx_th_form_005frow_005fbegin_005f2.setJspContext(_jspx_page_context);
    _jspx_th_form_005frow_005fbegin_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005frow_005fbegin_005f2);
    return false;
  }

  private boolean _jspx_meth_form_005flabel_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:label
    org.apache.jsp.tag.webform.label_tag _jspx_th_form_005flabel_005f2 = (new org.apache.jsp.tag.webform.label_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005flabel_005f2);
    _jspx_th_form_005flabel_005f2.setJspContext(_jspx_page_context);
    // /trampoline/scrapped/search.jsp(162,16) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005flabel_005f2.setName("");
    // /trampoline/scrapped/search.jsp(162,16) name = label type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005flabel_005f2.setLabel("");
    _jspx_th_form_005flabel_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005flabel_005f2);
    return false;
  }

  private boolean _jspx_meth_form_005fbuttonset_005fbegin_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:buttonset_begin
    org.apache.jsp.tag.webform.buttonset_005fbegin_tag _jspx_th_form_005fbuttonset_005fbegin_005f1 = (new org.apache.jsp.tag.webform.buttonset_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fbuttonset_005fbegin_005f1);
    _jspx_th_form_005fbuttonset_005fbegin_005f1.setJspContext(_jspx_page_context);
    // /trampoline/scrapped/search.jsp(163,16) name = align type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fbuttonset_005fbegin_005f1.setAlign("left");
    // /trampoline/scrapped/search.jsp(163,16) name = padding type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fbuttonset_005fbegin_005f1.setPadding("0");
    _jspx_th_form_005fbuttonset_005fbegin_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fbuttonset_005fbegin_005f1);
    return false;
  }

  private boolean _jspx_meth_form_005fsubmit_005finline_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:submit_inline
    org.apache.jsp.tag.webform.submit_005finline_tag _jspx_th_form_005fsubmit_005finline_005f1 = (new org.apache.jsp.tag.webform.submit_005finline_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fsubmit_005finline_005f1);
    _jspx_th_form_005fsubmit_005finline_005f1.setJspContext(_jspx_page_context);
    // /trampoline/scrapped/search.jsp(164,20) name = button type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f1.setButton("save");
    // /trampoline/scrapped/search.jsp(164,20) name = waiting type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f1.setWaiting("true");
    // /trampoline/scrapped/search.jsp(164,20) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f1.setName("Mark Scrapped");
    // /trampoline/scrapped/search.jsp(164,20) name = action type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f1.setAction("mark_scrapped");
    _jspx_th_form_005fsubmit_005finline_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fsubmit_005finline_005f1);
    return false;
  }

  private boolean _jspx_meth_form_005fbuttonset_005fend_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:buttonset_end
    org.apache.jsp.tag.webform.buttonset_005fend_tag _jspx_th_form_005fbuttonset_005fend_005f1 = (new org.apache.jsp.tag.webform.buttonset_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fbuttonset_005fend_005f1);
    _jspx_th_form_005fbuttonset_005fend_005f1.setJspContext(_jspx_page_context);
    _jspx_th_form_005fbuttonset_005fend_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fbuttonset_005fend_005f1);
    return false;
  }

  private boolean _jspx_meth_form_005frow_005fend_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:row_end
    org.apache.jsp.tag.webform.row_005fend_tag _jspx_th_form_005frow_005fend_005f2 = (new org.apache.jsp.tag.webform.row_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005frow_005fend_005f2);
    _jspx_th_form_005frow_005fend_005f2.setJspContext(_jspx_page_context);
    _jspx_th_form_005frow_005fend_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005frow_005fend_005f2);
    return false;
  }

  private boolean _jspx_meth_form_005fend_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:end
    org.apache.jsp.tag.webform.end_tag _jspx_th_form_005fend_005f1 = (new org.apache.jsp.tag.webform.end_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fend_005f1);
    _jspx_th_form_005fend_005f1.setJspContext(_jspx_page_context);
    _jspx_th_form_005fend_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fend_005f1);
    return false;
  }

  private boolean _jspx_meth_admin_005fbox_005fend_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:box_end
    org.apache.jsp.tag.webadmin.box_005fend_tag _jspx_th_admin_005fbox_005fend_005f2 = (new org.apache.jsp.tag.webadmin.box_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fbox_005fend_005f2);
    _jspx_th_admin_005fbox_005fend_005f2.setJspContext(_jspx_page_context);
    _jspx_th_admin_005fbox_005fend_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fbox_005fend_005f2);
    return false;
  }

  private boolean _jspx_meth_admin_005fsubtitle_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:subtitle
    org.apache.jsp.tag.webadmin.subtitle_tag _jspx_th_admin_005fsubtitle_005f1 = (new org.apache.jsp.tag.webadmin.subtitle_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fsubtitle_005f1);
    _jspx_th_admin_005fsubtitle_005f1.setJspContext(_jspx_page_context);
    // /trampoline/scrapped/search.jsp(174,4) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fsubtitle_005f1.setText("No Reels Found.");
    _jspx_th_admin_005fsubtitle_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fsubtitle_005f1);
    return false;
  }

  private boolean _jspx_meth_admin_005fset_005ftabset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:set_tabset
    org.apache.jsp.tag.webadmin.set_005ftabset_tag _jspx_th_admin_005fset_005ftabset_005f0 = (new org.apache.jsp.tag.webadmin.set_005ftabset_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fset_005ftabset_005f0);
    _jspx_th_admin_005fset_005ftabset_005f0.setJspContext(_jspx_page_context);
    // /trampoline/scrapped/search.jsp(178,0) name = url type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fset_005ftabset_005f0.setUrl("scrapped/_tabset_default.jsp");
    // /trampoline/scrapped/search.jsp(178,0) name = thispage type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fset_005ftabset_005f0.setThispage("search.jsp");
    _jspx_th_admin_005fset_005ftabset_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fset_005ftabset_005f0);
    return false;
  }

  private boolean _jspx_meth_html_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:end
    org.apache.jsp.tag.webhtml.end_tag _jspx_th_html_005fend_005f0 = (new org.apache.jsp.tag.webhtml.end_tag());
    _jsp_instancemanager.newInstance(_jspx_th_html_005fend_005f0);
    _jspx_th_html_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_html_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_html_005fend_005f0);
    return false;
  }
}
