/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2016-08-30 13:54:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.trampoline.reels;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.reeltrack.users.*;
import com.reeltrack.reels.*;
import com.monumental.trampoline.component.*;
import com.monumental.trampoline.utilities.text.*;

public final class notes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(34);
    _jspx_dependants.put("/WEB-INF/tags/form/row_begin.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/admin/subtitle.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/submit_inline.tag", Long.valueOf(1472425523000L));
    _jspx_dependants.put("/WEB-INF/tags/listing/row_end.tag", Long.valueOf(1472002170000L));
    _jspx_dependants.put("/WEB-INF/tags/admin/title.tag", Long.valueOf(1472493852000L));
    _jspx_dependants.put("/WEB-INF/tags/listing/end.tag", Long.valueOf(1472002170000L));
    _jspx_dependants.put("/WEB-INF/tags/admin/set_tabset.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/admin/box_end.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/checkbox.tag", Long.valueOf(1472495472000L));
    _jspx_dependants.put("/WEB-INF/tags/form/hidden.tag", Long.valueOf(1472002170000L));
    _jspx_dependants.put("/WEB-INF/tags/form/buttonset_end.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/html/end.tag", Long.valueOf(1472002193000L));
    _jspx_dependants.put("/WEB-INF/tags/listing/cell_begin.tag", Long.valueOf(1472002193000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1472002170000L));
    _jspx_dependants.put("/WEB-INF/tags/admin/box_begin.tag", Long.valueOf(1472498302000L));
    _jspx_dependants.put("/WEB-INF/tags/listing/header_begin.tag", Long.valueOf(1472002193000L));
    _jspx_dependants.put("/WEB-INF/tags/listing/row_begin.tag", Long.valueOf(1472002193000L));
    _jspx_dependants.put("/WEB-INF/tags/listing/begin.tag", Long.valueOf(1472002193000L));
    _jspx_dependants.put("/WEB-INF/tags/form/textarea.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/begin.tag", Long.valueOf(1472529757000L));
    _jspx_dependants.put("/WEB-INF/tags/listing/header_end.tag", Long.valueOf(1472002193000L));
    _jspx_dependants.put("jar:file:/www/new/tomcat/webapps/../../web/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098725490000L));
    _jspx_dependants.put("/WEB-INF/tags/html/begin.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/label.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/notifier/show_message.tag", Long.valueOf(1472002193000L));
    _jspx_dependants.put("jar:file:/www/new/tomcat/webapps/../../web/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098725490000L));
    _jspx_dependants.put("/WEB-INF/tags/form/end.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/listing/header_cell.tag", Long.valueOf(1472002193000L));
    _jspx_dependants.put("/WEB-INF/tags/form/label_inline.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/end_inline.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/row_end.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/listing/cell_end.tag", Long.valueOf(1472002170000L));
    _jspx_dependants.put("/WEB-INF/tags/form/buttonset_begin.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/trampoline/reels/../common/includes/only_users.jsp", Long.valueOf(1472002170000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\t\t\n");
      out.write("\n");
      out.write("\n");
      com.reeltrack.users.RTUserLoginMgr onlyuserLoginMgr = null;
      onlyuserLoginMgr = (com.reeltrack.users.RTUserLoginMgr) _jspx_page_context.getAttribute("onlyuserLoginMgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (onlyuserLoginMgr == null){
        onlyuserLoginMgr = new com.reeltrack.users.RTUserLoginMgr();
        _jspx_page_context.setAttribute("onlyuserLoginMgr", onlyuserLoginMgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
      out.write('\n');
 onlyuserLoginMgr.init(pageContext); 
      out.write('\n');
      out.write('\n');
 if(!onlyuserLoginMgr.isLoggedIn()) { 
      out.write("\n");
      out.write("\t<script type=\"text/javascript\" language=\"javascript\">\n");
      out.write("\t\t\t// first, if we're in the _submissionFrame, call window location on the parent\n");
      out.write("\t\t\tparent.window.location = \"");
      out.print( request.getContextPath() );
      out.write("/trampoline/index.jsp\";\n");
      out.write("\t\n");
      out.write("\t\t\t// otherwise, we'll be doing this on this window\n");
      out.write("\t\t\twindow.location = \"");
      out.print( request.getContextPath() );
      out.write("/trampoline/index.jsp\";\n");
      out.write("\t</script>\n");
 } 
      out.write('\n');
 if(!onlyuserLoginMgr.isLoggedIn()) return; 
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      com.monumental.trampoline.datasources.DbResources dbResources = null;
      dbResources = (com.monumental.trampoline.datasources.DbResources) _jspx_page_context.getAttribute("dbResources", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (dbResources == null){
        dbResources = new com.monumental.trampoline.datasources.DbResources();
        _jspx_page_context.setAttribute("dbResources", dbResources, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
      com.reeltrack.reels.ReelMgr reelMgr = null;
      reelMgr = (com.reeltrack.reels.ReelMgr) _jspx_page_context.getAttribute("reelMgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (reelMgr == null){
        reelMgr = new com.reeltrack.reels.ReelMgr();
        _jspx_page_context.setAttribute("reelMgr", reelMgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
      com.reeltrack.users.RTUserLoginMgr userLoginMgr = null;
      userLoginMgr = (com.reeltrack.users.RTUserLoginMgr) _jspx_page_context.getAttribute("userLoginMgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (userLoginMgr == null){
        userLoginMgr = new com.reeltrack.users.RTUserLoginMgr();
        _jspx_page_context.setAttribute("userLoginMgr", userLoginMgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
 userLoginMgr.init(pageContext); 
      out.write('\n');
 reelMgr.init(pageContext,dbResources); 
      out.write('\n');
 RTUser user = (RTUser)userLoginMgr.getUser(); 
      out.write('\n');

// Get the id
int contid = 0;
if(request.getParameter(Reel.PARAM) != null) {
    contid = Integer.parseInt(request.getParameter(Reel.PARAM));
} else {
    String param = "content_id_for_tabset";
    if(request.getParameter(param) != null) {
        contid = Integer.parseInt(request.getParameter(param));
    }
}

// Get the piece of content
Reel content = new Reel();
content.setId(contid);
content = (Reel)reelMgr.getReel(content);

CompEntities notes = reelMgr.getReelNotes(content);
ReelNote note;

String tempURL; //var for url expression

      out.write('\n');
 dbResources.close(); 
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_html_005fbegin_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_notifier_005fshow_005fmessage_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('\n');
 tempURL = content.getCrId() + " : " + content.getReelTag() + " : " +  content.getCableDescription(); 
      out.write('\n');
      //  admin:title
      org.apache.jsp.tag.webadmin.title_tag _jspx_th_admin_005ftitle_005f0 = (new org.apache.jsp.tag.webadmin.title_tag());
      _jsp_instancemanager.newInstance(_jspx_th_admin_005ftitle_005f0);
      _jspx_th_admin_005ftitle_005f0.setJspContext(_jspx_page_context);
      // /trampoline/reels/notes.jsp(56,0) name = heading type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_admin_005ftitle_005f0.setHeading("Reel Page");
      // /trampoline/reels/notes.jsp(56,0) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_admin_005ftitle_005f0.setText( tempURL );
      _jspx_th_admin_005ftitle_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_admin_005ftitle_005f0);
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_admin_005fsubtitle_005f0(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_admin_005fbox_005fbegin_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_form_005fbegin_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    \t\t");
      //  form:textarea
      org.apache.jsp.tag.webform.textarea_tag _jspx_th_form_005ftextarea_005f0 = (new org.apache.jsp.tag.webform.textarea_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005ftextarea_005f0);
      _jspx_th_form_005ftextarea_005f0.setJspContext(_jspx_page_context);
      // /trampoline/reels/notes.jsp(61,6) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextarea_005f0.setName( ReelNote.NOTE_COLUMN );
      // /trampoline/reels/notes.jsp(61,6) name = rows type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextarea_005f0.setRows("5");
      // /trampoline/reels/notes.jsp(61,6) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextarea_005f0.setLabel("Note:");
      // /trampoline/reels/notes.jsp(61,6) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextarea_005f0.setValue("");
      _jspx_th_form_005ftextarea_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005ftextarea_005f0);
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_form_005fcheckbox_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t");
      //  form:hidden
      org.apache.jsp.tag.webform.hidden_tag _jspx_th_form_005fhidden_005f0 = (new org.apache.jsp.tag.webform.hidden_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005fhidden_005f0);
      _jspx_th_form_005fhidden_005f0.setJspContext(_jspx_page_context);
      // /trampoline/reels/notes.jsp(63,3) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fhidden_005f0.setName( Reel.PARAM );
      // /trampoline/reels/notes.jsp(63,3) name = value type = java.lang.Object reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fhidden_005f0.setValue( new Integer(contid).toString() );
      _jspx_th_form_005fhidden_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005fhidden_005f0);
      out.write("\n");
      out.write("\t\t\t");
      if (_jspx_meth_form_005frow_005fbegin_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_form_005flabel_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_form_005fbuttonset_005fbegin_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_form_005fsubmit_005finline_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_form_005fbuttonset_005fend_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t");
      if (_jspx_meth_form_005frow_005fend_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_form_005fend_005f0(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_admin_005fbox_005fend_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('\n');
      out.write('\n');
 if(notes.howMany() > 0) { 
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_admin_005fsubtitle_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_admin_005fbox_005fbegin_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_listing_005fbegin_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_listing_005fheader_005fbegin_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fheader_005fcell_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fheader_005fcell_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fheader_005fcell_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_listing_005fheader_005fend_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
 for(int i=0; i<notes.howMany(); i++) { 
      out.write("\n");
      out.write("        ");
 note = (ReelNote)notes.get(i); 
      out.write("\n");
      out.write("        ");
      //  listing:row_begin
      org.apache.jsp.tag.weblisting.row_005fbegin_tag _jspx_th_listing_005frow_005fbegin_005f0 = (new org.apache.jsp.tag.weblisting.row_005fbegin_tag());
      _jsp_instancemanager.newInstance(_jspx_th_listing_005frow_005fbegin_005f0);
      _jspx_th_listing_005frow_005fbegin_005f0.setJspContext(_jspx_page_context);
      // /trampoline/reels/notes.jsp(85,8) name = row type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_listing_005frow_005fbegin_005f0.setRow( new Integer(i).toString() );
      _jspx_th_listing_005frow_005fbegin_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_listing_005frow_005fbegin_005f0);
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fcell_005fbegin_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                ");
      out.print( note.getCreatedDateText() );
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fcell_005fend_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fcell_005fbegin_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                ");
      out.print( note.getCreatedBy() );
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fcell_005fend_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fcell_005fbegin_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                ");
      out.print( TextParser.addBreakTags(note.getNote()) );
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fcell_005fend_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_listing_005frow_005fend_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_listing_005fend_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_admin_005fbox_005fend_005f1(_jspx_page_context))
        return;
      out.write('\n');
 } else { 
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_admin_005fsubtitle_005f2(_jspx_page_context))
        return;
      out.write('\n');
 } 
      out.write('\n');
      out.write('\n');
      //  admin:set_tabset
      org.apache.jsp.tag.webadmin.set_005ftabset_tag _jspx_th_admin_005fset_005ftabset_005f0 = (new org.apache.jsp.tag.webadmin.set_005ftabset_tag());
      _jsp_instancemanager.newInstance(_jspx_th_admin_005fset_005ftabset_005f0);
      _jspx_th_admin_005fset_005ftabset_005f0.setJspContext(_jspx_page_context);
      // /trampoline/reels/notes.jsp(103,0) name = url type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_admin_005fset_005ftabset_005f0.setUrl("reels/_tabset_manage.jsp");
      // /trampoline/reels/notes.jsp(103,0) name = thispage type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_admin_005fset_005ftabset_005f0.setThispage("notes.jsp");
      // /trampoline/reels/notes.jsp(103,0) name = content_id_for_tabset type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_admin_005fset_005ftabset_005f0.setContent_id_for_tabset( contid );
      _jspx_th_admin_005fset_005ftabset_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fset_005ftabset_005f0);
      out.write('\n');
      if (_jspx_meth_html_005fend_005f0(_jspx_page_context))
        return;
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_html_005fbegin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:begin
    org.apache.jsp.tag.webhtml.begin_tag _jspx_th_html_005fbegin_005f0 = (new org.apache.jsp.tag.webhtml.begin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_html_005fbegin_005f0);
    _jspx_th_html_005fbegin_005f0.setJspContext(_jspx_page_context);
    _jspx_th_html_005fbegin_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_html_005fbegin_005f0);
    return false;
  }

  private boolean _jspx_meth_notifier_005fshow_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  notifier:show_message
    org.apache.jsp.tag.webnotifier.show_005fmessage_tag _jspx_th_notifier_005fshow_005fmessage_005f0 = (new org.apache.jsp.tag.webnotifier.show_005fmessage_tag());
    _jsp_instancemanager.newInstance(_jspx_th_notifier_005fshow_005fmessage_005f0);
    _jspx_th_notifier_005fshow_005fmessage_005f0.setJspContext(_jspx_page_context);
    _jspx_th_notifier_005fshow_005fmessage_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_notifier_005fshow_005fmessage_005f0);
    return false;
  }

  private boolean _jspx_meth_admin_005fsubtitle_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:subtitle
    org.apache.jsp.tag.webadmin.subtitle_tag _jspx_th_admin_005fsubtitle_005f0 = (new org.apache.jsp.tag.webadmin.subtitle_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fsubtitle_005f0);
    _jspx_th_admin_005fsubtitle_005f0.setJspContext(_jspx_page_context);
    // /trampoline/reels/notes.jsp(58,0) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fsubtitle_005f0.setText("Add Note");
    _jspx_th_admin_005fsubtitle_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fsubtitle_005f0);
    return false;
  }

  private boolean _jspx_meth_admin_005fbox_005fbegin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:box_begin
    org.apache.jsp.tag.webadmin.box_005fbegin_tag _jspx_th_admin_005fbox_005fbegin_005f0 = (new org.apache.jsp.tag.webadmin.box_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fbox_005fbegin_005f0);
    _jspx_th_admin_005fbox_005fbegin_005f0.setJspContext(_jspx_page_context);
    _jspx_th_admin_005fbox_005fbegin_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fbox_005fbegin_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005fbegin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:begin
    org.apache.jsp.tag.webform.begin_tag _jspx_th_form_005fbegin_005f0 = (new org.apache.jsp.tag.webform.begin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fbegin_005f0);
    _jspx_th_form_005fbegin_005f0.setJspContext(_jspx_page_context);
    // /trampoline/reels/notes.jsp(60,4) name = submit type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fbegin_005f0.setSubmit("true");
    // /trampoline/reels/notes.jsp(60,4) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fbegin_005f0.setName("edit");
    // /trampoline/reels/notes.jsp(60,4) name = action type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fbegin_005f0.setAction("reels/process.jsp");
    _jspx_th_form_005fbegin_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fbegin_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005fcheckbox_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:checkbox
    org.apache.jsp.tag.webform.checkbox_tag _jspx_th_form_005fcheckbox_005f0 = (new org.apache.jsp.tag.webform.checkbox_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fcheckbox_005f0);
    _jspx_th_form_005fcheckbox_005f0.setJspContext(_jspx_page_context);
    // /trampoline/reels/notes.jsp(62,12) name = label type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fcheckbox_005f0.setLabel("Notify ECS?:");
    // /trampoline/reels/notes.jsp(62,12) name = text type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fcheckbox_005f0.setText("Send a copy of this note to ECS?");
    // /trampoline/reels/notes.jsp(62,12) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fcheckbox_005f0.setName("send_note");
    // /trampoline/reels/notes.jsp(62,12) name = value type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fcheckbox_005f0.setValue("y");
    _jspx_th_form_005fcheckbox_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fcheckbox_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005frow_005fbegin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:row_begin
    org.apache.jsp.tag.webform.row_005fbegin_tag _jspx_th_form_005frow_005fbegin_005f0 = (new org.apache.jsp.tag.webform.row_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005frow_005fbegin_005f0);
    _jspx_th_form_005frow_005fbegin_005f0.setJspContext(_jspx_page_context);
    _jspx_th_form_005frow_005fbegin_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005frow_005fbegin_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005flabel_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:label
    org.apache.jsp.tag.webform.label_tag _jspx_th_form_005flabel_005f0 = (new org.apache.jsp.tag.webform.label_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005flabel_005f0);
    _jspx_th_form_005flabel_005f0.setJspContext(_jspx_page_context);
    // /trampoline/reels/notes.jsp(65,4) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005flabel_005f0.setName("");
    // /trampoline/reels/notes.jsp(65,4) name = label type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005flabel_005f0.setLabel("");
    _jspx_th_form_005flabel_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005flabel_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005fbuttonset_005fbegin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:buttonset_begin
    org.apache.jsp.tag.webform.buttonset_005fbegin_tag _jspx_th_form_005fbuttonset_005fbegin_005f0 = (new org.apache.jsp.tag.webform.buttonset_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fbuttonset_005fbegin_005f0);
    _jspx_th_form_005fbuttonset_005fbegin_005f0.setJspContext(_jspx_page_context);
    // /trampoline/reels/notes.jsp(66,4) name = align type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fbuttonset_005fbegin_005f0.setAlign("left");
    // /trampoline/reels/notes.jsp(66,4) name = padding type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fbuttonset_005fbegin_005f0.setPadding("0");
    _jspx_th_form_005fbuttonset_005fbegin_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fbuttonset_005fbegin_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005fsubmit_005finline_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:submit_inline
    org.apache.jsp.tag.webform.submit_005finline_tag _jspx_th_form_005fsubmit_005finline_005f0 = (new org.apache.jsp.tag.webform.submit_005finline_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fsubmit_005finline_005f0);
    _jspx_th_form_005fsubmit_005finline_005f0.setJspContext(_jspx_page_context);
    // /trampoline/reels/notes.jsp(67,5) name = button type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f0.setButton("save");
    // /trampoline/reels/notes.jsp(67,5) name = waiting type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f0.setWaiting("true");
    // /trampoline/reels/notes.jsp(67,5) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f0.setName("save");
    // /trampoline/reels/notes.jsp(67,5) name = action type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f0.setAction("add_note");
    _jspx_th_form_005fsubmit_005finline_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fsubmit_005finline_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005fbuttonset_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:buttonset_end
    org.apache.jsp.tag.webform.buttonset_005fend_tag _jspx_th_form_005fbuttonset_005fend_005f0 = (new org.apache.jsp.tag.webform.buttonset_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fbuttonset_005fend_005f0);
    _jspx_th_form_005fbuttonset_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_form_005fbuttonset_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fbuttonset_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005frow_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:row_end
    org.apache.jsp.tag.webform.row_005fend_tag _jspx_th_form_005frow_005fend_005f0 = (new org.apache.jsp.tag.webform.row_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005frow_005fend_005f0);
    _jspx_th_form_005frow_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_form_005frow_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005frow_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:end
    org.apache.jsp.tag.webform.end_tag _jspx_th_form_005fend_005f0 = (new org.apache.jsp.tag.webform.end_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fend_005f0);
    _jspx_th_form_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_form_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_admin_005fbox_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:box_end
    org.apache.jsp.tag.webadmin.box_005fend_tag _jspx_th_admin_005fbox_005fend_005f0 = (new org.apache.jsp.tag.webadmin.box_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fbox_005fend_005f0);
    _jspx_th_admin_005fbox_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_admin_005fbox_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fbox_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_admin_005fsubtitle_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:subtitle
    org.apache.jsp.tag.webadmin.subtitle_tag _jspx_th_admin_005fsubtitle_005f1 = (new org.apache.jsp.tag.webadmin.subtitle_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fsubtitle_005f1);
    _jspx_th_admin_005fsubtitle_005f1.setJspContext(_jspx_page_context);
    // /trampoline/reels/notes.jsp(75,4) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fsubtitle_005f1.setText("All Notes");
    _jspx_th_admin_005fsubtitle_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fsubtitle_005f1);
    return false;
  }

  private boolean _jspx_meth_admin_005fbox_005fbegin_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:box_begin
    org.apache.jsp.tag.webadmin.box_005fbegin_tag _jspx_th_admin_005fbox_005fbegin_005f1 = (new org.apache.jsp.tag.webadmin.box_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fbox_005fbegin_005f1);
    _jspx_th_admin_005fbox_005fbegin_005f1.setJspContext(_jspx_page_context);
    // /trampoline/reels/notes.jsp(76,4) name = color type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fbox_005fbegin_005f1.setColor("false");
    _jspx_th_admin_005fbox_005fbegin_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fbox_005fbegin_005f1);
    return false;
  }

  private boolean _jspx_meth_listing_005fbegin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:begin
    org.apache.jsp.tag.weblisting.begin_tag _jspx_th_listing_005fbegin_005f0 = (new org.apache.jsp.tag.weblisting.begin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fbegin_005f0);
    _jspx_th_listing_005fbegin_005f0.setJspContext(_jspx_page_context);
    _jspx_th_listing_005fbegin_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fbegin_005f0);
    return false;
  }

  private boolean _jspx_meth_listing_005fheader_005fbegin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:header_begin
    org.apache.jsp.tag.weblisting.header_005fbegin_tag _jspx_th_listing_005fheader_005fbegin_005f0 = (new org.apache.jsp.tag.weblisting.header_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fheader_005fbegin_005f0);
    _jspx_th_listing_005fheader_005fbegin_005f0.setJspContext(_jspx_page_context);
    _jspx_th_listing_005fheader_005fbegin_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fheader_005fbegin_005f0);
    return false;
  }

  private boolean _jspx_meth_listing_005fheader_005fcell_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:header_cell
    org.apache.jsp.tag.weblisting.header_005fcell_tag _jspx_th_listing_005fheader_005fcell_005f0 = (new org.apache.jsp.tag.weblisting.header_005fcell_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fheader_005fcell_005f0);
    _jspx_th_listing_005fheader_005fcell_005f0.setJspContext(_jspx_page_context);
    // /trampoline/reels/notes.jsp(79,12) name = width type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_listing_005fheader_005fcell_005f0.setWidth("75");
    // /trampoline/reels/notes.jsp(79,12) name = first type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_listing_005fheader_005fcell_005f0.setFirst("true");
    // /trampoline/reels/notes.jsp(79,12) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_listing_005fheader_005fcell_005f0.setName("Created");
    _jspx_th_listing_005fheader_005fcell_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fheader_005fcell_005f0);
    return false;
  }

  private boolean _jspx_meth_listing_005fheader_005fcell_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:header_cell
    org.apache.jsp.tag.weblisting.header_005fcell_tag _jspx_th_listing_005fheader_005fcell_005f1 = (new org.apache.jsp.tag.weblisting.header_005fcell_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fheader_005fcell_005f1);
    _jspx_th_listing_005fheader_005fcell_005f1.setJspContext(_jspx_page_context);
    // /trampoline/reels/notes.jsp(80,12) name = width type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_listing_005fheader_005fcell_005f1.setWidth("100");
    // /trampoline/reels/notes.jsp(80,12) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_listing_005fheader_005fcell_005f1.setName("By User");
    _jspx_th_listing_005fheader_005fcell_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fheader_005fcell_005f1);
    return false;
  }

  private boolean _jspx_meth_listing_005fheader_005fcell_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:header_cell
    org.apache.jsp.tag.weblisting.header_005fcell_tag _jspx_th_listing_005fheader_005fcell_005f2 = (new org.apache.jsp.tag.weblisting.header_005fcell_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fheader_005fcell_005f2);
    _jspx_th_listing_005fheader_005fcell_005f2.setJspContext(_jspx_page_context);
    // /trampoline/reels/notes.jsp(81,12) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_listing_005fheader_005fcell_005f2.setName("Note");
    _jspx_th_listing_005fheader_005fcell_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fheader_005fcell_005f2);
    return false;
  }

  private boolean _jspx_meth_listing_005fheader_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:header_end
    org.apache.jsp.tag.weblisting.header_005fend_tag _jspx_th_listing_005fheader_005fend_005f0 = (new org.apache.jsp.tag.weblisting.header_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fheader_005fend_005f0);
    _jspx_th_listing_005fheader_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_listing_005fheader_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fheader_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_listing_005fcell_005fbegin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:cell_begin
    org.apache.jsp.tag.weblisting.cell_005fbegin_tag _jspx_th_listing_005fcell_005fbegin_005f0 = (new org.apache.jsp.tag.weblisting.cell_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fcell_005fbegin_005f0);
    _jspx_th_listing_005fcell_005fbegin_005f0.setJspContext(_jspx_page_context);
    _jspx_th_listing_005fcell_005fbegin_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fcell_005fbegin_005f0);
    return false;
  }

  private boolean _jspx_meth_listing_005fcell_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:cell_end
    org.apache.jsp.tag.weblisting.cell_005fend_tag _jspx_th_listing_005fcell_005fend_005f0 = (new org.apache.jsp.tag.weblisting.cell_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fcell_005fend_005f0);
    _jspx_th_listing_005fcell_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_listing_005fcell_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fcell_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_listing_005fcell_005fbegin_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:cell_begin
    org.apache.jsp.tag.weblisting.cell_005fbegin_tag _jspx_th_listing_005fcell_005fbegin_005f1 = (new org.apache.jsp.tag.weblisting.cell_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fcell_005fbegin_005f1);
    _jspx_th_listing_005fcell_005fbegin_005f1.setJspContext(_jspx_page_context);
    _jspx_th_listing_005fcell_005fbegin_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fcell_005fbegin_005f1);
    return false;
  }

  private boolean _jspx_meth_listing_005fcell_005fend_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:cell_end
    org.apache.jsp.tag.weblisting.cell_005fend_tag _jspx_th_listing_005fcell_005fend_005f1 = (new org.apache.jsp.tag.weblisting.cell_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fcell_005fend_005f1);
    _jspx_th_listing_005fcell_005fend_005f1.setJspContext(_jspx_page_context);
    _jspx_th_listing_005fcell_005fend_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fcell_005fend_005f1);
    return false;
  }

  private boolean _jspx_meth_listing_005fcell_005fbegin_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:cell_begin
    org.apache.jsp.tag.weblisting.cell_005fbegin_tag _jspx_th_listing_005fcell_005fbegin_005f2 = (new org.apache.jsp.tag.weblisting.cell_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fcell_005fbegin_005f2);
    _jspx_th_listing_005fcell_005fbegin_005f2.setJspContext(_jspx_page_context);
    _jspx_th_listing_005fcell_005fbegin_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fcell_005fbegin_005f2);
    return false;
  }

  private boolean _jspx_meth_listing_005fcell_005fend_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:cell_end
    org.apache.jsp.tag.weblisting.cell_005fend_tag _jspx_th_listing_005fcell_005fend_005f2 = (new org.apache.jsp.tag.weblisting.cell_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fcell_005fend_005f2);
    _jspx_th_listing_005fcell_005fend_005f2.setJspContext(_jspx_page_context);
    _jspx_th_listing_005fcell_005fend_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fcell_005fend_005f2);
    return false;
  }

  private boolean _jspx_meth_listing_005frow_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:row_end
    org.apache.jsp.tag.weblisting.row_005fend_tag _jspx_th_listing_005frow_005fend_005f0 = (new org.apache.jsp.tag.weblisting.row_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005frow_005fend_005f0);
    _jspx_th_listing_005frow_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_listing_005frow_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005frow_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_listing_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:end
    org.apache.jsp.tag.weblisting.end_tag _jspx_th_listing_005fend_005f0 = (new org.apache.jsp.tag.weblisting.end_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fend_005f0);
    _jspx_th_listing_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_listing_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_admin_005fbox_005fend_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:box_end
    org.apache.jsp.tag.webadmin.box_005fend_tag _jspx_th_admin_005fbox_005fend_005f1 = (new org.apache.jsp.tag.webadmin.box_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fbox_005fend_005f1);
    _jspx_th_admin_005fbox_005fend_005f1.setJspContext(_jspx_page_context);
    _jspx_th_admin_005fbox_005fend_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fbox_005fend_005f1);
    return false;
  }

  private boolean _jspx_meth_admin_005fsubtitle_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:subtitle
    org.apache.jsp.tag.webadmin.subtitle_tag _jspx_th_admin_005fsubtitle_005f2 = (new org.apache.jsp.tag.webadmin.subtitle_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fsubtitle_005f2);
    _jspx_th_admin_005fsubtitle_005f2.setJspContext(_jspx_page_context);
    // /trampoline/reels/notes.jsp(100,4) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fsubtitle_005f2.setText("There are no Notes.");
    _jspx_th_admin_005fsubtitle_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fsubtitle_005f2);
    return false;
  }

  private boolean _jspx_meth_html_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:end
    org.apache.jsp.tag.webhtml.end_tag _jspx_th_html_005fend_005f0 = (new org.apache.jsp.tag.webhtml.end_tag());
    _jsp_instancemanager.newInstance(_jspx_th_html_005fend_005f0);
    _jspx_th_html_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_html_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_html_005fend_005f0);
    return false;
  }
}
