/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2016-08-30 13:54:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.trampoline.reels;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.reeltrack.users.*;
import com.reeltrack.reels.*;
import com.monumental.trampoline.component.*;
import com.monumental.trampoline.utilities.text.*;
import java.net.*;

public final class reel_005fdata_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(32);
    _jspx_dependants.put("/WEB-INF/tags/form/row_begin.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/admin/subtitle.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/file.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/submit_inline.tag", Long.valueOf(1472425523000L));
    _jspx_dependants.put("/WEB-INF/tags/admin/title.tag", Long.valueOf(1472493852000L));
    _jspx_dependants.put("/WEB-INF/tags/admin/link.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/admin/set_tabset.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/info.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/textfield.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/admin/box_end.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/buttonset_end.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/hidden.tag", Long.valueOf(1472002170000L));
    _jspx_dependants.put("/WEB-INF/tags/html/end.tag", Long.valueOf(1472002193000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1472002170000L));
    _jspx_dependants.put("/WEB-INF/tags/admin/box_begin.tag", Long.valueOf(1472498302000L));
    _jspx_dependants.put("/WEB-INF/tags/form/linkbutton.tag", Long.valueOf(1472521293000L));
    _jspx_dependants.put("/WEB-INF/tags/form/content_begin.tag", Long.valueOf(1472496815000L));
    _jspx_dependants.put("/WEB-INF/tags/form/content_end.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/begin_multipart.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/begin.tag", Long.valueOf(1472529757000L));
    _jspx_dependants.put("jar:file:/www/new/tomcat/webapps/../../web/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098725490000L));
    _jspx_dependants.put("/WEB-INF/tags/html/begin.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/label.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/notifier/show_message.tag", Long.valueOf(1472002193000L));
    _jspx_dependants.put("jar:file:/www/new/tomcat/webapps/../../web/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098725490000L));
    _jspx_dependants.put("/WEB-INF/tags/form/end.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/label_inline.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/end_inline.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/row_end.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/buttonset_begin.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/date_picker.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/trampoline/reels/../common/includes/only_users.jsp", Long.valueOf(1472002170000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\t\t\n");
      out.write("\n");
      out.write("\n");
      com.reeltrack.users.RTUserLoginMgr onlyuserLoginMgr = null;
      onlyuserLoginMgr = (com.reeltrack.users.RTUserLoginMgr) _jspx_page_context.getAttribute("onlyuserLoginMgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (onlyuserLoginMgr == null){
        onlyuserLoginMgr = new com.reeltrack.users.RTUserLoginMgr();
        _jspx_page_context.setAttribute("onlyuserLoginMgr", onlyuserLoginMgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
      out.write('\n');
 onlyuserLoginMgr.init(pageContext); 
      out.write('\n');
      out.write('\n');
 if(!onlyuserLoginMgr.isLoggedIn()) { 
      out.write("\n");
      out.write("\t<script type=\"text/javascript\" language=\"javascript\">\n");
      out.write("\t\t\t// first, if we're in the _submissionFrame, call window location on the parent\n");
      out.write("\t\t\tparent.window.location = \"");
      out.print( request.getContextPath() );
      out.write("/trampoline/index.jsp\";\n");
      out.write("\t\n");
      out.write("\t\t\t// otherwise, we'll be doing this on this window\n");
      out.write("\t\t\twindow.location = \"");
      out.print( request.getContextPath() );
      out.write("/trampoline/index.jsp\";\n");
      out.write("\t</script>\n");
 } 
      out.write('\n');
 if(!onlyuserLoginMgr.isLoggedIn()) return; 
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      com.monumental.trampoline.datasources.DbResources dbResources = null;
      dbResources = (com.monumental.trampoline.datasources.DbResources) _jspx_page_context.getAttribute("dbResources", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (dbResources == null){
        dbResources = new com.monumental.trampoline.datasources.DbResources();
        _jspx_page_context.setAttribute("dbResources", dbResources, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
      com.reeltrack.reels.ReelMgr reelMgr = null;
      reelMgr = (com.reeltrack.reels.ReelMgr) _jspx_page_context.getAttribute("reelMgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (reelMgr == null){
        reelMgr = new com.reeltrack.reels.ReelMgr();
        _jspx_page_context.setAttribute("reelMgr", reelMgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
      com.reeltrack.users.RTUserLoginMgr userLoginMgr = null;
      userLoginMgr = (com.reeltrack.users.RTUserLoginMgr) _jspx_page_context.getAttribute("userLoginMgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (userLoginMgr == null){
        userLoginMgr = new com.reeltrack.users.RTUserLoginMgr();
        _jspx_page_context.setAttribute("userLoginMgr", userLoginMgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
 userLoginMgr.init(pageContext); 
      out.write('\n');
 reelMgr.init(pageContext,dbResources); 
      out.write('\n');
 RTUser user = (RTUser)userLoginMgr.getUser(); 
      out.write('\n');

boolean canEdit = false;
if(user.isUserType(RTUser.USER_TYPE_ECS)) {
    canEdit = true;
}

      out.write('\n');

// Get the id
int contid = 0;
if(request.getParameter(Reel.PARAM) != null) {
    contid = Integer.parseInt(request.getParameter(Reel.PARAM));
} else {
    String param = "content_id_for_tabset";
    if(request.getParameter(param) != null) {
        contid = Integer.parseInt(request.getParameter(param));
    }
}

// Get the piece of content
Reel content = new Reel();
content.setId(contid);
content = (Reel)reelMgr.getReel(content);

String tempURL; //var for url expression

      out.write('\n');
 dbResources.close(); 
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_html_005fbegin_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_notifier_005fshow_005fmessage_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('\n');
 tempURL = content.getCrId() + " : " + content.getReelTag() + " : " +  content.getCableDescription(); 
      out.write('\n');
      //  admin:title
      org.apache.jsp.tag.webadmin.title_tag _jspx_th_admin_005ftitle_005f0 = (new org.apache.jsp.tag.webadmin.title_tag());
      _jsp_instancemanager.newInstance(_jspx_th_admin_005ftitle_005f0);
      _jspx_th_admin_005ftitle_005f0.setJspContext(_jspx_page_context);
      // /trampoline/reels/reel_data.jsp(60,0) name = heading type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_admin_005ftitle_005f0.setHeading("Reel Page");
      // /trampoline/reels/reel_data.jsp(60,0) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_admin_005ftitle_005f0.setText( tempURL );
      _jspx_th_admin_005ftitle_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_admin_005ftitle_005f0);
      out.write('\n');
      out.write('\n');
 if(canEdit) { 
      out.write('\n');
      if (_jspx_meth_admin_005fsubtitle_005f0(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_admin_005fbox_005fbegin_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
      //  form:begin
      org.apache.jsp.tag.webform.begin_tag _jspx_th_form_005fbegin_005f0 = (new org.apache.jsp.tag.webform.begin_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005fbegin_005f0);
      _jspx_th_form_005fbegin_005f0.setJspContext(_jspx_page_context);
      // /trampoline/reels/reel_data.jsp(65,4) name = submit type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fbegin_005f0.setSubmit( new Boolean(false).toString() );
      // /trampoline/reels/reel_data.jsp(65,4) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fbegin_005f0.setName("edit");
      // /trampoline/reels/reel_data.jsp(65,4) name = action type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fbegin_005f0.setAction("reels/process.jsp");
      _jspx_th_form_005fbegin_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005fbegin_005f0);
      out.write('\n');
      out.write('	');
      out.write('	');
      //  form:textfield
      org.apache.jsp.tag.webform.textfield_tag _jspx_th_form_005ftextfield_005f0 = (new org.apache.jsp.tag.webform.textfield_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005ftextfield_005f0);
      _jspx_th_form_005ftextfield_005f0.setJspContext(_jspx_page_context);
      // /trampoline/reels/reel_data.jsp(66,2) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f0.setLabel("Unique ID:");
      // /trampoline/reels/reel_data.jsp(66,2) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f0.setName( Reel.UNIQUE_ID_COLUMN );
      // /trampoline/reels/reel_data.jsp(66,2) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f0.setValue( new Integer(content.getUniqueId()).toString() );
      _jspx_th_form_005ftextfield_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005ftextfield_005f0);
      out.write('\n');
      out.write('	');
      out.write('	');
      if (_jspx_meth_form_005frow_005fbegin_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t");
      if (_jspx_meth_form_005flabel_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t");
      if (_jspx_meth_form_005fbuttonset_005fbegin_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t");
 if(canEdit) { 
      out.write("\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_form_005fsubmit_005finline_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t");
      if (_jspx_meth_form_005fbuttonset_005fend_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('	');
      out.write('	');
      if (_jspx_meth_form_005frow_005fend_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
      //  form:hidden
      org.apache.jsp.tag.webform.hidden_tag _jspx_th_form_005fhidden_005f0 = (new org.apache.jsp.tag.webform.hidden_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005fhidden_005f0);
      _jspx_th_form_005fhidden_005f0.setJspContext(_jspx_page_context);
      // /trampoline/reels/reel_data.jsp(75,8) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fhidden_005f0.setName( Reel.PARAM );
      // /trampoline/reels/reel_data.jsp(75,8) name = value type = java.lang.Object reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fhidden_005f0.setValue( new Integer(contid).toString() );
      _jspx_th_form_005fhidden_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005fhidden_005f0);
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_form_005fend_005f0(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_admin_005fbox_005fend_005f0(_jspx_page_context))
        return;
      out.write('\n');
 } 
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_admin_005fsubtitle_005f1(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_admin_005fbox_005fbegin_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
      //  form:begin
      org.apache.jsp.tag.webform.begin_tag _jspx_th_form_005fbegin_005f1 = (new org.apache.jsp.tag.webform.begin_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005fbegin_005f1);
      _jspx_th_form_005fbegin_005f1.setJspContext(_jspx_page_context);
      // /trampoline/reels/reel_data.jsp(82,4) name = submit type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fbegin_005f1.setSubmit( new Boolean(false).toString() );
      // /trampoline/reels/reel_data.jsp(82,4) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fbegin_005f1.setName("edit");
      // /trampoline/reels/reel_data.jsp(82,4) name = action type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fbegin_005f1.setAction("reels/process.jsp");
      _jspx_th_form_005fbegin_005f1.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005fbegin_005f1);
      out.write("\n");
      out.write("        ");
 if(!canEdit) { 
      out.write("\n");
      out.write("            ");
      //  form:info
      org.apache.jsp.tag.webform.info_tag _jspx_th_form_005finfo_005f0 = (new org.apache.jsp.tag.webform.info_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005finfo_005f0);
      _jspx_th_form_005finfo_005f0.setJspContext(_jspx_page_context);
      // /trampoline/reels/reel_data.jsp(84,12) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f0.setLabel("Customer PO:");
      // /trampoline/reels/reel_data.jsp(84,12) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f0.setText( content.getCustomerPO() );
      _jspx_th_form_005finfo_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005finfo_005f0);
      out.write("\n");
      out.write("            ");
      //  form:info
      org.apache.jsp.tag.webform.info_tag _jspx_th_form_005finfo_005f1 = (new org.apache.jsp.tag.webform.info_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005finfo_005f1);
      _jspx_th_form_005finfo_005f1.setJspContext(_jspx_page_context);
      // /trampoline/reels/reel_data.jsp(85,12) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f1.setLabel("Invoice #:");
      // /trampoline/reels/reel_data.jsp(85,12) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f1.setText( content.getInvoiceNum() );
      _jspx_th_form_005finfo_005f1.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005finfo_005f1);
      out.write("\n");
      out.write("            ");
      //  form:info
      org.apache.jsp.tag.webform.info_tag _jspx_th_form_005finfo_005f2 = (new org.apache.jsp.tag.webform.info_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005finfo_005f2);
      _jspx_th_form_005finfo_005f2.setJspContext(_jspx_page_context);
      // /trampoline/reels/reel_data.jsp(86,12) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f2.setLabel("Invoice Date:");
      // /trampoline/reels/reel_data.jsp(86,12) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f2.setText( content.getInvoiceDateString() );
      _jspx_th_form_005finfo_005f2.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005finfo_005f2);
      out.write("\n");
      out.write("        ");
 } else { 
      out.write("\n");
      out.write("            ");
      //  form:info
      org.apache.jsp.tag.webform.info_tag _jspx_th_form_005finfo_005f3 = (new org.apache.jsp.tag.webform.info_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005finfo_005f3);
      _jspx_th_form_005finfo_005f3.setJspContext(_jspx_page_context);
      // /trampoline/reels/reel_data.jsp(88,12) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f3.setLabel("ECS PO:");
      // /trampoline/reels/reel_data.jsp(88,12) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f3.setText( content.getOrdNo() );
      _jspx_th_form_005finfo_005f3.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005finfo_005f3);
      out.write("\n");
      out.write("            ");
      //  form:textfield
      org.apache.jsp.tag.webform.textfield_tag _jspx_th_form_005ftextfield_005f1 = (new org.apache.jsp.tag.webform.textfield_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005ftextfield_005f1);
      _jspx_th_form_005ftextfield_005f1.setJspContext(_jspx_page_context);
      // /trampoline/reels/reel_data.jsp(89,12) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f1.setLabel("Customer PO:");
      // /trampoline/reels/reel_data.jsp(89,12) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f1.setName( Reel.CUSTOMER_PO_COLUMN );
      // /trampoline/reels/reel_data.jsp(89,12) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f1.setValue( content.getCustomerPO() );
      _jspx_th_form_005ftextfield_005f1.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005ftextfield_005f1);
      out.write("\n");
      out.write("            ");
      //  form:textfield
      org.apache.jsp.tag.webform.textfield_tag _jspx_th_form_005ftextfield_005f2 = (new org.apache.jsp.tag.webform.textfield_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005ftextfield_005f2);
      _jspx_th_form_005ftextfield_005f2.setJspContext(_jspx_page_context);
      // /trampoline/reels/reel_data.jsp(90,12) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f2.setLabel("Invoice #:");
      // /trampoline/reels/reel_data.jsp(90,12) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f2.setName( Reel.INVOICE_NUM_COLUMN );
      // /trampoline/reels/reel_data.jsp(90,12) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f2.setValue( content.getInvoiceNum() );
      _jspx_th_form_005ftextfield_005f2.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005ftextfield_005f2);
      out.write("\n");
      out.write("            ");
      //  form:date_picker
      org.apache.jsp.tag.webform.date_005fpicker_tag _jspx_th_form_005fdate_005fpicker_005f0 = (new org.apache.jsp.tag.webform.date_005fpicker_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005fdate_005fpicker_005f0);
      _jspx_th_form_005fdate_005fpicker_005f0.setJspContext(_jspx_page_context);
      // /trampoline/reels/reel_data.jsp(91,12) name = start type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fdate_005fpicker_005f0.setStart("01/01/2014");
      // /trampoline/reels/reel_data.jsp(91,12) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fdate_005fpicker_005f0.setName( Reel.INVOICE_DATE_COLUMN );
      // /trampoline/reels/reel_data.jsp(91,12) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fdate_005fpicker_005f0.setValue( content.getInvoiceDateString() );
      // /trampoline/reels/reel_data.jsp(91,12) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fdate_005fpicker_005f0.setLabel("Invoice Date:");
      _jspx_th_form_005fdate_005fpicker_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005fdate_005fpicker_005f0);
      out.write("\n");
      out.write("            ");
      //  form:hidden
      org.apache.jsp.tag.webform.hidden_tag _jspx_th_form_005fhidden_005f1 = (new org.apache.jsp.tag.webform.hidden_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005fhidden_005f1);
      _jspx_th_form_005fhidden_005f1.setJspContext(_jspx_page_context);
      // /trampoline/reels/reel_data.jsp(92,12) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fhidden_005f1.setName( Reel.PARAM );
      // /trampoline/reels/reel_data.jsp(92,12) name = value type = java.lang.Object reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fhidden_005f1.setValue( new Integer(contid).toString() );
      _jspx_th_form_005fhidden_005f1.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005fhidden_005f1);
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_form_005frow_005fbegin_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                ");
      if (_jspx_meth_form_005flabel_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                ");
      if (_jspx_meth_form_005fbuttonset_005fbegin_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                    ");
 if(canEdit) { 
      out.write("\n");
      out.write("                    ");
      if (_jspx_meth_form_005fsubmit_005finline_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                ");
      if (_jspx_meth_form_005fbuttonset_005fend_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_form_005frow_005fend_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_form_005fend_005f1(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_admin_005fbox_005fend_005f1(_jspx_page_context))
        return;
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_admin_005fsubtitle_005f2(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_admin_005fbox_005fbegin_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
      //  form:begin_multipart
      org.apache.jsp.tag.webform.begin_005fmultipart_tag _jspx_th_form_005fbegin_005fmultipart_005f0 = (new org.apache.jsp.tag.webform.begin_005fmultipart_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005fbegin_005fmultipart_005f0);
      _jspx_th_form_005fbegin_005fmultipart_005f0.setJspContext(_jspx_page_context);
      // /trampoline/reels/reel_data.jsp(107,4) name = submit type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fbegin_005fmultipart_005f0.setSubmit( new Boolean(canEdit).toString() );
      // /trampoline/reels/reel_data.jsp(107,4) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fbegin_005fmultipart_005f0.setName("edit");
      // /trampoline/reels/reel_data.jsp(107,4) name = action type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fbegin_005fmultipart_005f0.setAction("reels/process.jsp");
      _jspx_th_form_005fbegin_005fmultipart_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005fbegin_005fmultipart_005f0);
      out.write("\n");
      out.write("        ");
      //  form:info
      org.apache.jsp.tag.webform.info_tag _jspx_th_form_005finfo_005f4 = (new org.apache.jsp.tag.webform.info_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005finfo_005f4);
      _jspx_th_form_005finfo_005f4.setJspContext(_jspx_page_context);
      // /trampoline/reels/reel_data.jsp(108,8) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f4.setLabel("CTR #:");
      // /trampoline/reels/reel_data.jsp(108,8) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f4.setText( content.getCTRNumber() );
      _jspx_th_form_005finfo_005f4.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005finfo_005f4);
      out.write("\n");
      out.write("        ");
      //  form:info
      org.apache.jsp.tag.webform.info_tag _jspx_th_form_005finfo_005f5 = (new org.apache.jsp.tag.webform.info_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005finfo_005f5);
      _jspx_th_form_005finfo_005f5.setJspContext(_jspx_page_context);
      // /trampoline/reels/reel_data.jsp(109,8) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f5.setLabel("CTR Date:");
      // /trampoline/reels/reel_data.jsp(109,8) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f5.setText( content.getCTRDateString() );
      _jspx_th_form_005finfo_005f5.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005finfo_005f5);
      out.write("\n");
      out.write("        ");
      //  form:info
      org.apache.jsp.tag.webform.info_tag _jspx_th_form_005finfo_005f6 = (new org.apache.jsp.tag.webform.info_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005finfo_005f6);
      _jspx_th_form_005finfo_005f6.setJspContext(_jspx_page_context);
      // /trampoline/reels/reel_data.jsp(110,8) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f6.setLabel("CTR Posted:");
      // /trampoline/reels/reel_data.jsp(110,8) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005finfo_005f6.setText( content.getCTRSentString() );
      _jspx_th_form_005finfo_005f6.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005finfo_005f6);
      out.write("\n");
      out.write("        ");
 if(canEdit) { 
      out.write('\n');
      out.write('	');
      out.write('	');
      //  form:file
      org.apache.jsp.tag.webform.file_tag _jspx_th_form_005ffile_005f0 = (new org.apache.jsp.tag.webform.file_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005ffile_005f0);
      _jspx_th_form_005ffile_005f0.setJspContext(_jspx_page_context);
      // /trampoline/reels/reel_data.jsp(112,2) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ffile_005f0.setName( Reel.CTR_FILE_COLUMN );
      // /trampoline/reels/reel_data.jsp(112,2) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ffile_005f0.setLabel("CTR File:");
      _jspx_th_form_005ffile_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005ffile_005f0);
      out.write("\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        ");
 if(content.getCTRFile() != null && !content.getCTRFile().equals("")) { 
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_form_005frow_005fbegin_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_form_005flabel_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_form_005fcontent_005fbegin_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                    ");
 tempURL = request.getContextPath() + content.getCompEntityDirectory() + "/" + URLEncoder.encode(content.getCTRFile()); 
      out.write("\n");
      out.write("                    ");
      //  admin:link
      org.apache.jsp.tag.webadmin.link_tag _jspx_th_admin_005flink_005f0 = (new org.apache.jsp.tag.webadmin.link_tag());
      _jsp_instancemanager.newInstance(_jspx_th_admin_005flink_005f0);
      _jspx_th_admin_005flink_005f0.setJspContext(_jspx_page_context);
      // /trampoline/reels/reel_data.jsp(119,20) name = external type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_admin_005flink_005f0.setExternal("true");
      // /trampoline/reels/reel_data.jsp(119,20) name = text type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_admin_005flink_005f0.setText("[Download]");
      // /trampoline/reels/reel_data.jsp(119,20) name = url type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_admin_005flink_005f0.setUrl( tempURL );
      _jspx_th_admin_005flink_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_admin_005flink_005f0);
      out.write("\n");
      out.write("                ");
      if (_jspx_meth_form_005fcontent_005fend_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_form_005frow_005fend_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
 if(canEdit) { 
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_form_005frow_005fbegin_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_form_005flabel_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_form_005fcontent_005fbegin_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                    ");
 String tempUrl = "reels/process.jsp?submit_action=delete_ctr&" + Reel.PARAM + "=" + content.getId(); 
      out.write("\n");
      out.write("                    ");
      //  form:linkbutton
      org.apache.jsp.tag.webform.linkbutton_tag _jspx_th_form_005flinkbutton_005f0 = (new org.apache.jsp.tag.webform.linkbutton_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005flinkbutton_005f0);
      _jspx_th_form_005flinkbutton_005f0.setJspContext(_jspx_page_context);
      // /trampoline/reels/reel_data.jsp(127,20) name = warning type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005flinkbutton_005f0.setWarning("true");
      // /trampoline/reels/reel_data.jsp(127,20) name = url type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005flinkbutton_005f0.setUrl( tempUrl );
      // /trampoline/reels/reel_data.jsp(127,20) name = process type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005flinkbutton_005f0.setProcess("true");
      // /trampoline/reels/reel_data.jsp(127,20) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005flinkbutton_005f0.setName("DELETE");
      _jspx_th_form_005flinkbutton_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005flinkbutton_005f0);
      out.write("\n");
      out.write("                ");
      if (_jspx_meth_form_005fcontent_005fend_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_form_005frow_005fend_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        ");
 } 
      out.write('\n');
      out.write('	');
      out.write('	');
      //  form:hidden
      org.apache.jsp.tag.webform.hidden_tag _jspx_th_form_005fhidden_005f2 = (new org.apache.jsp.tag.webform.hidden_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005fhidden_005f2);
      _jspx_th_form_005fhidden_005f2.setJspContext(_jspx_page_context);
      // /trampoline/reels/reel_data.jsp(132,2) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fhidden_005f2.setName( Reel.PARAM );
      // /trampoline/reels/reel_data.jsp(132,2) name = value type = java.lang.Object reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fhidden_005f2.setValue( new Integer(contid).toString() );
      _jspx_th_form_005fhidden_005f2.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005fhidden_005f2);
      out.write('\n');
      out.write('	');
      out.write('	');
      if (_jspx_meth_form_005frow_005fbegin_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t");
      if (_jspx_meth_form_005flabel_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t");
      if (_jspx_meth_form_005fbuttonset_005fbegin_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                ");
 if(canEdit) { 
      out.write("\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_form_005fsubmit_005finline_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("\t\t\t");
      if (_jspx_meth_form_005fbuttonset_005fend_005f2(_jspx_page_context))
        return;
      out.write('\n');
      out.write('	');
      out.write('	');
      if (_jspx_meth_form_005frow_005fend_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_form_005fend_005f2(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_admin_005fbox_005fend_005f2(_jspx_page_context))
        return;
      out.write('\n');
      out.write('\n');
      out.write('\n');
      //  admin:set_tabset
      org.apache.jsp.tag.webadmin.set_005ftabset_tag _jspx_th_admin_005fset_005ftabset_005f0 = (new org.apache.jsp.tag.webadmin.set_005ftabset_tag());
      _jsp_instancemanager.newInstance(_jspx_th_admin_005fset_005ftabset_005f0);
      _jspx_th_admin_005fset_005ftabset_005f0.setJspContext(_jspx_page_context);
      // /trampoline/reels/reel_data.jsp(145,0) name = url type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_admin_005fset_005ftabset_005f0.setUrl("reels/_tabset_manage.jsp");
      // /trampoline/reels/reel_data.jsp(145,0) name = thispage type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_admin_005fset_005ftabset_005f0.setThispage("reel_data.jsp");
      // /trampoline/reels/reel_data.jsp(145,0) name = content_id_for_tabset type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_admin_005fset_005ftabset_005f0.setContent_id_for_tabset( contid );
      _jspx_th_admin_005fset_005ftabset_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fset_005ftabset_005f0);
      out.write('\n');
      if (_jspx_meth_html_005fend_005f0(_jspx_page_context))
        return;
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_html_005fbegin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:begin
    org.apache.jsp.tag.webhtml.begin_tag _jspx_th_html_005fbegin_005f0 = (new org.apache.jsp.tag.webhtml.begin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_html_005fbegin_005f0);
    _jspx_th_html_005fbegin_005f0.setJspContext(_jspx_page_context);
    _jspx_th_html_005fbegin_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_html_005fbegin_005f0);
    return false;
  }

  private boolean _jspx_meth_notifier_005fshow_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  notifier:show_message
    org.apache.jsp.tag.webnotifier.show_005fmessage_tag _jspx_th_notifier_005fshow_005fmessage_005f0 = (new org.apache.jsp.tag.webnotifier.show_005fmessage_tag());
    _jsp_instancemanager.newInstance(_jspx_th_notifier_005fshow_005fmessage_005f0);
    _jspx_th_notifier_005fshow_005fmessage_005f0.setJspContext(_jspx_page_context);
    _jspx_th_notifier_005fshow_005fmessage_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_notifier_005fshow_005fmessage_005f0);
    return false;
  }

  private boolean _jspx_meth_admin_005fsubtitle_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:subtitle
    org.apache.jsp.tag.webadmin.subtitle_tag _jspx_th_admin_005fsubtitle_005f0 = (new org.apache.jsp.tag.webadmin.subtitle_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fsubtitle_005f0);
    _jspx_th_admin_005fsubtitle_005f0.setJspContext(_jspx_page_context);
    // /trampoline/reels/reel_data.jsp(63,0) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fsubtitle_005f0.setText("Unique ID");
    _jspx_th_admin_005fsubtitle_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fsubtitle_005f0);
    return false;
  }

  private boolean _jspx_meth_admin_005fbox_005fbegin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:box_begin
    org.apache.jsp.tag.webadmin.box_005fbegin_tag _jspx_th_admin_005fbox_005fbegin_005f0 = (new org.apache.jsp.tag.webadmin.box_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fbox_005fbegin_005f0);
    _jspx_th_admin_005fbox_005fbegin_005f0.setJspContext(_jspx_page_context);
    // /trampoline/reels/reel_data.jsp(64,0) name = text type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fbox_005fbegin_005f0.setText("Unique ID");
    // /trampoline/reels/reel_data.jsp(64,0) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fbox_005fbegin_005f0.setName("Unique_ID");
    _jspx_th_admin_005fbox_005fbegin_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fbox_005fbegin_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005frow_005fbegin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:row_begin
    org.apache.jsp.tag.webform.row_005fbegin_tag _jspx_th_form_005frow_005fbegin_005f0 = (new org.apache.jsp.tag.webform.row_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005frow_005fbegin_005f0);
    _jspx_th_form_005frow_005fbegin_005f0.setJspContext(_jspx_page_context);
    _jspx_th_form_005frow_005fbegin_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005frow_005fbegin_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005flabel_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:label
    org.apache.jsp.tag.webform.label_tag _jspx_th_form_005flabel_005f0 = (new org.apache.jsp.tag.webform.label_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005flabel_005f0);
    _jspx_th_form_005flabel_005f0.setJspContext(_jspx_page_context);
    // /trampoline/reels/reel_data.jsp(68,3) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005flabel_005f0.setName("");
    // /trampoline/reels/reel_data.jsp(68,3) name = label type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005flabel_005f0.setLabel("");
    _jspx_th_form_005flabel_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005flabel_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005fbuttonset_005fbegin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:buttonset_begin
    org.apache.jsp.tag.webform.buttonset_005fbegin_tag _jspx_th_form_005fbuttonset_005fbegin_005f0 = (new org.apache.jsp.tag.webform.buttonset_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fbuttonset_005fbegin_005f0);
    _jspx_th_form_005fbuttonset_005fbegin_005f0.setJspContext(_jspx_page_context);
    // /trampoline/reels/reel_data.jsp(69,3) name = align type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fbuttonset_005fbegin_005f0.setAlign("left");
    // /trampoline/reels/reel_data.jsp(69,3) name = padding type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fbuttonset_005fbegin_005f0.setPadding("0");
    _jspx_th_form_005fbuttonset_005fbegin_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fbuttonset_005fbegin_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005fsubmit_005finline_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:submit_inline
    org.apache.jsp.tag.webform.submit_005finline_tag _jspx_th_form_005fsubmit_005finline_005f0 = (new org.apache.jsp.tag.webform.submit_005finline_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fsubmit_005finline_005f0);
    _jspx_th_form_005fsubmit_005finline_005f0.setJspContext(_jspx_page_context);
    // /trampoline/reels/reel_data.jsp(71,4) name = button type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f0.setButton("save");
    // /trampoline/reels/reel_data.jsp(71,4) name = waiting type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f0.setWaiting("true");
    // /trampoline/reels/reel_data.jsp(71,4) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f0.setName("save");
    // /trampoline/reels/reel_data.jsp(71,4) name = action type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f0.setAction("update_unique_id");
    _jspx_th_form_005fsubmit_005finline_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fsubmit_005finline_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005fbuttonset_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:buttonset_end
    org.apache.jsp.tag.webform.buttonset_005fend_tag _jspx_th_form_005fbuttonset_005fend_005f0 = (new org.apache.jsp.tag.webform.buttonset_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fbuttonset_005fend_005f0);
    _jspx_th_form_005fbuttonset_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_form_005fbuttonset_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fbuttonset_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005frow_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:row_end
    org.apache.jsp.tag.webform.row_005fend_tag _jspx_th_form_005frow_005fend_005f0 = (new org.apache.jsp.tag.webform.row_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005frow_005fend_005f0);
    _jspx_th_form_005frow_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_form_005frow_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005frow_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:end
    org.apache.jsp.tag.webform.end_tag _jspx_th_form_005fend_005f0 = (new org.apache.jsp.tag.webform.end_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fend_005f0);
    _jspx_th_form_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_form_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_admin_005fbox_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:box_end
    org.apache.jsp.tag.webadmin.box_005fend_tag _jspx_th_admin_005fbox_005fend_005f0 = (new org.apache.jsp.tag.webadmin.box_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fbox_005fend_005f0);
    _jspx_th_admin_005fbox_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_admin_005fbox_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fbox_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_admin_005fsubtitle_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:subtitle
    org.apache.jsp.tag.webadmin.subtitle_tag _jspx_th_admin_005fsubtitle_005f1 = (new org.apache.jsp.tag.webadmin.subtitle_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fsubtitle_005f1);
    _jspx_th_admin_005fsubtitle_005f1.setJspContext(_jspx_page_context);
    // /trampoline/reels/reel_data.jsp(80,0) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fsubtitle_005f1.setText("ECS Invoice");
    _jspx_th_admin_005fsubtitle_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fsubtitle_005f1);
    return false;
  }

  private boolean _jspx_meth_admin_005fbox_005fbegin_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:box_begin
    org.apache.jsp.tag.webadmin.box_005fbegin_tag _jspx_th_admin_005fbox_005fbegin_005f1 = (new org.apache.jsp.tag.webadmin.box_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fbox_005fbegin_005f1);
    _jspx_th_admin_005fbox_005fbegin_005f1.setJspContext(_jspx_page_context);
    // /trampoline/reels/reel_data.jsp(81,0) name = text type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fbox_005fbegin_005f1.setText("ECS Invoice");
    // /trampoline/reels/reel_data.jsp(81,0) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fbox_005fbegin_005f1.setName("ECS_Invoice");
    _jspx_th_admin_005fbox_005fbegin_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fbox_005fbegin_005f1);
    return false;
  }

  private boolean _jspx_meth_form_005frow_005fbegin_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:row_begin
    org.apache.jsp.tag.webform.row_005fbegin_tag _jspx_th_form_005frow_005fbegin_005f1 = (new org.apache.jsp.tag.webform.row_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005frow_005fbegin_005f1);
    _jspx_th_form_005frow_005fbegin_005f1.setJspContext(_jspx_page_context);
    _jspx_th_form_005frow_005fbegin_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005frow_005fbegin_005f1);
    return false;
  }

  private boolean _jspx_meth_form_005flabel_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:label
    org.apache.jsp.tag.webform.label_tag _jspx_th_form_005flabel_005f1 = (new org.apache.jsp.tag.webform.label_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005flabel_005f1);
    _jspx_th_form_005flabel_005f1.setJspContext(_jspx_page_context);
    // /trampoline/reels/reel_data.jsp(94,16) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005flabel_005f1.setName("");
    // /trampoline/reels/reel_data.jsp(94,16) name = label type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005flabel_005f1.setLabel("");
    _jspx_th_form_005flabel_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005flabel_005f1);
    return false;
  }

  private boolean _jspx_meth_form_005fbuttonset_005fbegin_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:buttonset_begin
    org.apache.jsp.tag.webform.buttonset_005fbegin_tag _jspx_th_form_005fbuttonset_005fbegin_005f1 = (new org.apache.jsp.tag.webform.buttonset_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fbuttonset_005fbegin_005f1);
    _jspx_th_form_005fbuttonset_005fbegin_005f1.setJspContext(_jspx_page_context);
    // /trampoline/reels/reel_data.jsp(95,16) name = align type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fbuttonset_005fbegin_005f1.setAlign("left");
    // /trampoline/reels/reel_data.jsp(95,16) name = padding type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fbuttonset_005fbegin_005f1.setPadding("0");
    _jspx_th_form_005fbuttonset_005fbegin_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fbuttonset_005fbegin_005f1);
    return false;
  }

  private boolean _jspx_meth_form_005fsubmit_005finline_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:submit_inline
    org.apache.jsp.tag.webform.submit_005finline_tag _jspx_th_form_005fsubmit_005finline_005f1 = (new org.apache.jsp.tag.webform.submit_005finline_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fsubmit_005finline_005f1);
    _jspx_th_form_005fsubmit_005finline_005f1.setJspContext(_jspx_page_context);
    // /trampoline/reels/reel_data.jsp(97,20) name = button type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f1.setButton("save");
    // /trampoline/reels/reel_data.jsp(97,20) name = waiting type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f1.setWaiting("true");
    // /trampoline/reels/reel_data.jsp(97,20) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f1.setName("save");
    // /trampoline/reels/reel_data.jsp(97,20) name = action type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f1.setAction("update_reel_invoice");
    _jspx_th_form_005fsubmit_005finline_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fsubmit_005finline_005f1);
    return false;
  }

  private boolean _jspx_meth_form_005fbuttonset_005fend_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:buttonset_end
    org.apache.jsp.tag.webform.buttonset_005fend_tag _jspx_th_form_005fbuttonset_005fend_005f1 = (new org.apache.jsp.tag.webform.buttonset_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fbuttonset_005fend_005f1);
    _jspx_th_form_005fbuttonset_005fend_005f1.setJspContext(_jspx_page_context);
    _jspx_th_form_005fbuttonset_005fend_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fbuttonset_005fend_005f1);
    return false;
  }

  private boolean _jspx_meth_form_005frow_005fend_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:row_end
    org.apache.jsp.tag.webform.row_005fend_tag _jspx_th_form_005frow_005fend_005f1 = (new org.apache.jsp.tag.webform.row_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005frow_005fend_005f1);
    _jspx_th_form_005frow_005fend_005f1.setJspContext(_jspx_page_context);
    _jspx_th_form_005frow_005fend_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005frow_005fend_005f1);
    return false;
  }

  private boolean _jspx_meth_form_005fend_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:end
    org.apache.jsp.tag.webform.end_tag _jspx_th_form_005fend_005f1 = (new org.apache.jsp.tag.webform.end_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fend_005f1);
    _jspx_th_form_005fend_005f1.setJspContext(_jspx_page_context);
    _jspx_th_form_005fend_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fend_005f1);
    return false;
  }

  private boolean _jspx_meth_admin_005fbox_005fend_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:box_end
    org.apache.jsp.tag.webadmin.box_005fend_tag _jspx_th_admin_005fbox_005fend_005f1 = (new org.apache.jsp.tag.webadmin.box_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fbox_005fend_005f1);
    _jspx_th_admin_005fbox_005fend_005f1.setJspContext(_jspx_page_context);
    _jspx_th_admin_005fbox_005fend_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fbox_005fend_005f1);
    return false;
  }

  private boolean _jspx_meth_admin_005fsubtitle_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:subtitle
    org.apache.jsp.tag.webadmin.subtitle_tag _jspx_th_admin_005fsubtitle_005f2 = (new org.apache.jsp.tag.webadmin.subtitle_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fsubtitle_005f2);
    _jspx_th_admin_005fsubtitle_005f2.setJspContext(_jspx_page_context);
    // /trampoline/reels/reel_data.jsp(105,0) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fsubtitle_005f2.setText("Reel Data");
    _jspx_th_admin_005fsubtitle_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fsubtitle_005f2);
    return false;
  }

  private boolean _jspx_meth_admin_005fbox_005fbegin_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:box_begin
    org.apache.jsp.tag.webadmin.box_005fbegin_tag _jspx_th_admin_005fbox_005fbegin_005f2 = (new org.apache.jsp.tag.webadmin.box_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fbox_005fbegin_005f2);
    _jspx_th_admin_005fbox_005fbegin_005f2.setJspContext(_jspx_page_context);
    // /trampoline/reels/reel_data.jsp(106,0) name = text type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fbox_005fbegin_005f2.setText("Reel Data");
    // /trampoline/reels/reel_data.jsp(106,0) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fbox_005fbegin_005f2.setName("Reel_Data");
    _jspx_th_admin_005fbox_005fbegin_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fbox_005fbegin_005f2);
    return false;
  }

  private boolean _jspx_meth_form_005frow_005fbegin_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:row_begin
    org.apache.jsp.tag.webform.row_005fbegin_tag _jspx_th_form_005frow_005fbegin_005f2 = (new org.apache.jsp.tag.webform.row_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005frow_005fbegin_005f2);
    _jspx_th_form_005frow_005fbegin_005f2.setJspContext(_jspx_page_context);
    _jspx_th_form_005frow_005fbegin_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005frow_005fbegin_005f2);
    return false;
  }

  private boolean _jspx_meth_form_005flabel_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:label
    org.apache.jsp.tag.webform.label_tag _jspx_th_form_005flabel_005f2 = (new org.apache.jsp.tag.webform.label_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005flabel_005f2);
    _jspx_th_form_005flabel_005f2.setJspContext(_jspx_page_context);
    // /trampoline/reels/reel_data.jsp(116,12) name = label type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005flabel_005f2.setLabel("Download CTR:");
    _jspx_th_form_005flabel_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005flabel_005f2);
    return false;
  }

  private boolean _jspx_meth_form_005fcontent_005fbegin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:content_begin
    org.apache.jsp.tag.webform.content_005fbegin_tag _jspx_th_form_005fcontent_005fbegin_005f0 = (new org.apache.jsp.tag.webform.content_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fcontent_005fbegin_005f0);
    _jspx_th_form_005fcontent_005fbegin_005f0.setJspContext(_jspx_page_context);
    _jspx_th_form_005fcontent_005fbegin_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fcontent_005fbegin_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005fcontent_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:content_end
    org.apache.jsp.tag.webform.content_005fend_tag _jspx_th_form_005fcontent_005fend_005f0 = (new org.apache.jsp.tag.webform.content_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fcontent_005fend_005f0);
    _jspx_th_form_005fcontent_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_form_005fcontent_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fcontent_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005frow_005fend_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:row_end
    org.apache.jsp.tag.webform.row_005fend_tag _jspx_th_form_005frow_005fend_005f2 = (new org.apache.jsp.tag.webform.row_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005frow_005fend_005f2);
    _jspx_th_form_005frow_005fend_005f2.setJspContext(_jspx_page_context);
    _jspx_th_form_005frow_005fend_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005frow_005fend_005f2);
    return false;
  }

  private boolean _jspx_meth_form_005frow_005fbegin_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:row_begin
    org.apache.jsp.tag.webform.row_005fbegin_tag _jspx_th_form_005frow_005fbegin_005f3 = (new org.apache.jsp.tag.webform.row_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005frow_005fbegin_005f3);
    _jspx_th_form_005frow_005fbegin_005f3.setJspContext(_jspx_page_context);
    _jspx_th_form_005frow_005fbegin_005f3.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005frow_005fbegin_005f3);
    return false;
  }

  private boolean _jspx_meth_form_005flabel_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:label
    org.apache.jsp.tag.webform.label_tag _jspx_th_form_005flabel_005f3 = (new org.apache.jsp.tag.webform.label_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005flabel_005f3);
    _jspx_th_form_005flabel_005f3.setJspContext(_jspx_page_context);
    // /trampoline/reels/reel_data.jsp(124,12) name = label type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005flabel_005f3.setLabel("Delete CTR:");
    _jspx_th_form_005flabel_005f3.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005flabel_005f3);
    return false;
  }

  private boolean _jspx_meth_form_005fcontent_005fbegin_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:content_begin
    org.apache.jsp.tag.webform.content_005fbegin_tag _jspx_th_form_005fcontent_005fbegin_005f1 = (new org.apache.jsp.tag.webform.content_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fcontent_005fbegin_005f1);
    _jspx_th_form_005fcontent_005fbegin_005f1.setJspContext(_jspx_page_context);
    _jspx_th_form_005fcontent_005fbegin_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fcontent_005fbegin_005f1);
    return false;
  }

  private boolean _jspx_meth_form_005fcontent_005fend_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:content_end
    org.apache.jsp.tag.webform.content_005fend_tag _jspx_th_form_005fcontent_005fend_005f1 = (new org.apache.jsp.tag.webform.content_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fcontent_005fend_005f1);
    _jspx_th_form_005fcontent_005fend_005f1.setJspContext(_jspx_page_context);
    _jspx_th_form_005fcontent_005fend_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fcontent_005fend_005f1);
    return false;
  }

  private boolean _jspx_meth_form_005frow_005fend_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:row_end
    org.apache.jsp.tag.webform.row_005fend_tag _jspx_th_form_005frow_005fend_005f3 = (new org.apache.jsp.tag.webform.row_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005frow_005fend_005f3);
    _jspx_th_form_005frow_005fend_005f3.setJspContext(_jspx_page_context);
    _jspx_th_form_005frow_005fend_005f3.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005frow_005fend_005f3);
    return false;
  }

  private boolean _jspx_meth_form_005frow_005fbegin_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:row_begin
    org.apache.jsp.tag.webform.row_005fbegin_tag _jspx_th_form_005frow_005fbegin_005f4 = (new org.apache.jsp.tag.webform.row_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005frow_005fbegin_005f4);
    _jspx_th_form_005frow_005fbegin_005f4.setJspContext(_jspx_page_context);
    _jspx_th_form_005frow_005fbegin_005f4.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005frow_005fbegin_005f4);
    return false;
  }

  private boolean _jspx_meth_form_005flabel_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:label
    org.apache.jsp.tag.webform.label_tag _jspx_th_form_005flabel_005f4 = (new org.apache.jsp.tag.webform.label_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005flabel_005f4);
    _jspx_th_form_005flabel_005f4.setJspContext(_jspx_page_context);
    // /trampoline/reels/reel_data.jsp(134,3) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005flabel_005f4.setName("");
    // /trampoline/reels/reel_data.jsp(134,3) name = label type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005flabel_005f4.setLabel("");
    _jspx_th_form_005flabel_005f4.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005flabel_005f4);
    return false;
  }

  private boolean _jspx_meth_form_005fbuttonset_005fbegin_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:buttonset_begin
    org.apache.jsp.tag.webform.buttonset_005fbegin_tag _jspx_th_form_005fbuttonset_005fbegin_005f2 = (new org.apache.jsp.tag.webform.buttonset_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fbuttonset_005fbegin_005f2);
    _jspx_th_form_005fbuttonset_005fbegin_005f2.setJspContext(_jspx_page_context);
    // /trampoline/reels/reel_data.jsp(135,3) name = align type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fbuttonset_005fbegin_005f2.setAlign("left");
    // /trampoline/reels/reel_data.jsp(135,3) name = padding type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fbuttonset_005fbegin_005f2.setPadding("0");
    _jspx_th_form_005fbuttonset_005fbegin_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fbuttonset_005fbegin_005f2);
    return false;
  }

  private boolean _jspx_meth_form_005fsubmit_005finline_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:submit_inline
    org.apache.jsp.tag.webform.submit_005finline_tag _jspx_th_form_005fsubmit_005finline_005f2 = (new org.apache.jsp.tag.webform.submit_005finline_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fsubmit_005finline_005f2);
    _jspx_th_form_005fsubmit_005finline_005f2.setJspContext(_jspx_page_context);
    // /trampoline/reels/reel_data.jsp(137,4) name = button type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f2.setButton("save");
    // /trampoline/reels/reel_data.jsp(137,4) name = waiting type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f2.setWaiting("true");
    // /trampoline/reels/reel_data.jsp(137,4) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f2.setName("save");
    // /trampoline/reels/reel_data.jsp(137,4) name = action type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f2.setAction("update_reel_data");
    _jspx_th_form_005fsubmit_005finline_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fsubmit_005finline_005f2);
    return false;
  }

  private boolean _jspx_meth_form_005fbuttonset_005fend_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:buttonset_end
    org.apache.jsp.tag.webform.buttonset_005fend_tag _jspx_th_form_005fbuttonset_005fend_005f2 = (new org.apache.jsp.tag.webform.buttonset_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fbuttonset_005fend_005f2);
    _jspx_th_form_005fbuttonset_005fend_005f2.setJspContext(_jspx_page_context);
    _jspx_th_form_005fbuttonset_005fend_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fbuttonset_005fend_005f2);
    return false;
  }

  private boolean _jspx_meth_form_005frow_005fend_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:row_end
    org.apache.jsp.tag.webform.row_005fend_tag _jspx_th_form_005frow_005fend_005f4 = (new org.apache.jsp.tag.webform.row_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005frow_005fend_005f4);
    _jspx_th_form_005frow_005fend_005f4.setJspContext(_jspx_page_context);
    _jspx_th_form_005frow_005fend_005f4.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005frow_005fend_005f4);
    return false;
  }

  private boolean _jspx_meth_form_005fend_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:end
    org.apache.jsp.tag.webform.end_tag _jspx_th_form_005fend_005f2 = (new org.apache.jsp.tag.webform.end_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fend_005f2);
    _jspx_th_form_005fend_005f2.setJspContext(_jspx_page_context);
    _jspx_th_form_005fend_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fend_005f2);
    return false;
  }

  private boolean _jspx_meth_admin_005fbox_005fend_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:box_end
    org.apache.jsp.tag.webadmin.box_005fend_tag _jspx_th_admin_005fbox_005fend_005f2 = (new org.apache.jsp.tag.webadmin.box_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fbox_005fend_005f2);
    _jspx_th_admin_005fbox_005fend_005f2.setJspContext(_jspx_page_context);
    _jspx_th_admin_005fbox_005fend_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fbox_005fend_005f2);
    return false;
  }

  private boolean _jspx_meth_html_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:end
    org.apache.jsp.tag.webhtml.end_tag _jspx_th_html_005fend_005f0 = (new org.apache.jsp.tag.webhtml.end_tag());
    _jsp_instancemanager.newInstance(_jspx_th_html_005fend_005f0);
    _jspx_th_html_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_html_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_html_005fend_005f0);
    return false;
  }
}
