/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2016-08-30 10:36:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag.webform;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class linkbutton_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent {


  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1472002170000L));
    _jspx_dependants.put("jar:file:/www/new/tomcat/webapps/../../web/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098725490000L));
    _jspx_dependants.put("jar:file:/www/new/tomcat/webapps/../../web/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098725490000L));
  }

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }
  private java.lang.String name;
  private java.lang.String button;
  private java.lang.String url;
  private java.lang.String process;
  private java.lang.String waiting;
  private java.lang.String warning;
  private java.lang.String cb_content;
  private java.lang.String tooltip;
  private java.lang.String newtab;

  public java.lang.String getName() {
    return this.name;
  }

  public void setName(java.lang.String name) {
    this.name = name;
    jspContext.setAttribute("name", name);
  }

  public java.lang.String getButton() {
    return this.button;
  }

  public void setButton(java.lang.String button) {
    this.button = button;
    jspContext.setAttribute("button", button);
  }

  public java.lang.String getUrl() {
    return this.url;
  }

  public void setUrl(java.lang.String url) {
    this.url = url;
    jspContext.setAttribute("url", url);
  }

  public java.lang.String getProcess() {
    return this.process;
  }

  public void setProcess(java.lang.String process) {
    this.process = process;
    jspContext.setAttribute("process", process);
  }

  public java.lang.String getWaiting() {
    return this.waiting;
  }

  public void setWaiting(java.lang.String waiting) {
    this.waiting = waiting;
    jspContext.setAttribute("waiting", waiting);
  }

  public java.lang.String getWarning() {
    return this.warning;
  }

  public void setWarning(java.lang.String warning) {
    this.warning = warning;
    jspContext.setAttribute("warning", warning);
  }

  public java.lang.String getCb_content() {
    return this.cb_content;
  }

  public void setCb_content(java.lang.String cb_content) {
    this.cb_content = cb_content;
    jspContext.setAttribute("cb_content", cb_content);
  }

  public java.lang.String getTooltip() {
    return this.tooltip;
  }

  public void setTooltip(java.lang.String tooltip) {
    this.tooltip = tooltip;
    jspContext.setAttribute("tooltip", tooltip);
  }

  public java.lang.String getNewtab() {
    return this.newtab;
  }

  public void setNewtab(java.lang.String newtab) {
    this.newtab = newtab;
    jspContext.setAttribute("newtab", newtab);
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
    javax.servlet.jsp.PageContext _jspx_page_context = (javax.servlet.jsp.PageContext)jspContext;
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    javax.servlet.http.HttpSession session = _jspx_page_context.getSession();
    javax.servlet.ServletContext application = _jspx_page_context.getServletContext();
    javax.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    javax.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,jspContext);
    if( getName() != null ) 
      _jspx_page_context.setAttribute("name", getName());
    if( getButton() != null ) 
      _jspx_page_context.setAttribute("button", getButton());
    if( getUrl() != null ) 
      _jspx_page_context.setAttribute("url", getUrl());
    if( getProcess() != null ) 
      _jspx_page_context.setAttribute("process", getProcess());
    if( getWaiting() != null ) 
      _jspx_page_context.setAttribute("waiting", getWaiting());
    if( getWarning() != null ) 
      _jspx_page_context.setAttribute("warning", getWarning());
    if( getCb_content() != null ) 
      _jspx_page_context.setAttribute("cb_content", getCb_content());
    if( getTooltip() != null ) 
      _jspx_page_context.setAttribute("tooltip", getTooltip());
    if( getNewtab() != null ) 
      _jspx_page_context.setAttribute("newtab", getNewtab());

    try {
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
 if(name.equalsIgnoreCase("duplicate")) { 
      out.write('\n');
      out.write('	');
if(tooltip != null) { 
      out.write("\n");
      out.write("\t\t<a data-toggle=\"tooltip\" title=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tooltip}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\" style=\"padding-left:2px;\" href=\"javascript:loadProcess('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("');\"><span class=\"glyphicon glyphicon-log-in\" style=\"color:#016b8d;font-size:24px;\"></span></a>\n");
      out.write("\t");
} else { 
      out.write("\n");
      out.write("\t\t<a style=\"padding-left:2px;\" href=\"javascript:loadProcess('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("');\"><span class=\"glyphicon glyphicon-log-in\" style=\"color:#016b8d;font-size:24px;\"></span></a>\n");
      out.write("\t");
 } 
      out.write('\n');
 } else if(name.equalsIgnoreCase("delete")) { 
      out.write('\n');
      out.write('	');
if(tooltip != null) { 
      out.write("\n");
      out.write("\t\t<a data-toggle=\"tooltip\" title=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tooltip}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\" style=\"padding-left:2px;\" href=\"javascript:loadProcessWithWarning('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("',this,'Are you sure you want to Delete?');\"><span class=\"glyphicon glyphicon-remove\" style=\"color:red;font-size:24px;\"></span></a>\n");
      out.write("\t");
} else { 
      out.write("\n");
      out.write("\t\t<a style=\"padding-left:2px;\" href=\"javascript:loadProcessWithWarning('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("',this,'Are you sure you want to Delete?');\"><span class=\"glyphicon glyphicon-remove\" style=\"color:red;font-size:24px;\"></span></a>\n");
      out.write("\t");
 } 
      out.write('\n');
 } else if(name.equalsIgnoreCase("evaluate")) { 
      out.write('\n');
      out.write('	');
if(tooltip != null) { 
      out.write("\n");
      out.write("\t\t<a data-toggle=\"tooltip\" title=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tooltip}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\" style=\"padding-left:2px;\" href=\"javascript:loadProcess('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("',this);\"><span class=\"glyphicon glyphicon-time\" style=\"color:#016b8d;font-size:24px;\"></span></a>\n");
      out.write("\t");
} else { 
      out.write("\n");
      out.write("\t\t<a style=\"padding-left:2px;\" href=\"javascript:loadProcess('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("',this);\"><span class=\"glyphicon glyphicon-time\" style=\"color:#016b8d;font-size:24px;\"></span></a>\n");
      out.write("\t");
 } 
      out.write('\n');
 } else if(name.equalsIgnoreCase("evaluate_passthru")) { 
      out.write('\n');
      out.write('	');
if(tooltip != null) { 
      out.write("\n");
      out.write("\t\t<a data-toggle=\"tooltip\" title=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tooltip}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\" style=\"padding-left:2px;cursor: pointer;\" onclick=\"javascript:loadProcess('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("',this);\"><span class=\"glyphicon glyphicon-ok-circle\" style=\"color:#016b8d;font-size:24px;\"></span></a>\n");
      out.write("\t");
} else { 
      out.write("\n");
      out.write("\t\t<a style=\"padding-left:2px;cursor: pointer;\" onclick=\"javascript:loadProcess('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("',this);\"><span class=\"glyphicon glyphicon-ok-circle\" style=\"color:#016b8d;font-size:24px;\"></span></a>\n");
      out.write("\t");
 } 
      out.write('\n');
 } else if(name.equalsIgnoreCase("score_passthru")) { 
      out.write('\n');
      out.write('	');
if(tooltip != null) { 
      out.write("\n");
      out.write("\t\t<a data-toggle=\"tooltip\" title=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tooltip}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\" style=\"padding-left:2px;cursor: pointer;\" onclick=\"javascript:loadProcessWithWarning('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("',this, 'Are you sure you want to Run Score?');\"><span class=\"glyphicon glyphicon-record\" style=\"color:#016b8d;font-size:24px;\"></span></a>\n");
      out.write("\t");
} else { 
      out.write("\n");
      out.write("\t\t<a style=\"padding-left:2px;cursor: pointer;\" onclick=\"javascript:loadProcessWithWarning('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("',this,'Are you sure you want to Run Score?');\"><span class=\"glyphicon glyphicon-record\" style=\"color:#016b8d;font-size:24px;\"></span></a>\n");
      out.write("\t");
 } 
      out.write('\n');
 } else if(name.equalsIgnoreCase("prescore_passthru")) { 
      out.write('\n');
      out.write('	');
if(tooltip != null) { 
      out.write("\n");
      out.write("\t\t<a data-toggle=\"tooltip\" title=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tooltip}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\" style=\"padding-left:2px;cursor: pointer;\" onclick=\"javascript:loadProcess('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("',this);\"><span class=\"glyphicon glyphicon-retweet\" style=\"color:#016b8d;font-size:24px;\"></span></a>\n");
      out.write("\t");
} else { 
      out.write("\n");
      out.write("\t\t<a style=\"padding-left:2px;cursor: pointer;\" onclick=\"javascript:loadProcess('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("',this);\"><span class=\"glyphicon glyphicon-retweet\" style=\"color:#016b8d;font-size:24px;\"></span></a>\n");
      out.write("\t");
 } 
      out.write('\n');
 } else if(name.equalsIgnoreCase("download")) { 
      out.write('\n');
      out.write('	');
if(tooltip != null) { 
      out.write("\n");
      out.write("\t\t<a data-toggle=\"tooltip\" title=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tooltip}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\" style=\"padding-left:2px;\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\" target=\"_new\"><span class=\"glyphicon glyphicon-cloud-download\" style=\"color:#016b8d;font-size:24px;\"></span></a>\n");
      out.write("\t");
} else { 
      out.write("\n");
      out.write("\t\t<a style=\"padding-left:2px;\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\" target=\"_new\"><span class=\"glyphicon glyphicon-cloud-download\" style=\"color:#016b8d;font-size:24px;\"></span></a>\n");
      out.write("\t");
 } 
      out.write('\n');
 } else if(name.equalsIgnoreCase("edit")) { 
      out.write('\n');
      out.write('	');
if(tooltip != null) { 
      out.write("\n");
      out.write("\t\t<a data-toggle=\"tooltip\" title=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tooltip}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\" style=\"padding-left:2px;cursor: pointer;\" onclick=\"javascript:loadTab('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("');\"><span class=\"glyphicon glyphicon-edit\" style=\"color:#016b8d;font-size:24px;\"></span></a>\n");
      out.write("\t");
} else { 
      out.write("\n");
      out.write("\t\t<a style=\"padding-left:2px;cursor: pointer;\" onclick=\"javascript:loadTab('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("');\"><span class=\"glyphicon glyphicon-edit\" style=\"color:#016b8d;font-size:24px;\"></span></a>\n");
      out.write("\t");
 } 
      out.write('\n');
 } else if(name.equalsIgnoreCase("reel page")) { 
      out.write('\n');
      out.write('	');
if(tooltip != null) { 
      out.write("\n");
      out.write("\t\t<a data-toggle=\"tooltip\" title=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tooltip}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\" style=\"padding-left:2px;cursor: pointer;\" onclick=\"javascript:loadTab('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("');\"><span class=\"glyphicon glyphicon-edit\" style=\"color:#016b8d;font-size:24px;\"></span></a>\n");
      out.write("\t");
} else { 
      out.write("\n");
      out.write("\t\t<a style=\"padding-left:2px;cursor: pointer;\" onclick=\"javascript:loadTab('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("');\"><span class=\"glyphicon glyphicon-edit\" style=\"color:#016b8d;font-size:24px;\"></span></a>\n");
      out.write("\t");
 } 
      out.write('\n');
 } else if(name.equalsIgnoreCase("locked")) { 
      out.write('\n');
      out.write('	');
if(tooltip != null) { 
      out.write("\n");
      out.write("\t\t<a data-toggle=\"tooltip\" title=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tooltip}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\" style=\"padding-left:2px;cursor: pointer;\"><span class=\"glyphicon glyphicon-lock\" style=\"color:#016b8d;font-size:24px;\"></span></a>\n");
      out.write("\t");
} else { 
      out.write("\n");
      out.write("\t\t<a style=\"padding-left:2px;cursor: pointer;\"><span class=\"glyphicon glyphicon-lock\" style=\"color:#016b8d;font-size:24px;\"></span></a>\n");
      out.write("\t");
 } 
      out.write('\n');
 } else if(name.equalsIgnoreCase("add")) { 
      out.write('\n');
      out.write('	');
if(tooltip != null) { 
      out.write("\n");
      out.write("\t\t<a data-toggle=\"tooltip\" title=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tooltip}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\" style=\"padding-left:2px;cursor: pointer;\" onclick=\"javascript:loadProcess('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("');\"><span class=\"glyphicon glyphicon-plus-sign\" style=\"color:#016b8d;font-size:24px;\"></span></a>\n");
      out.write("\t");
} else { 
      out.write("\n");
      out.write("\t\t<a style=\"padding-left:2px;cursor: pointer;\" onclick=\"javascript:loadProcess('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("');\"><span class=\"glyphicon glyphicon-plus-sign\" style=\"color:#016b8d;font-size:24px;\"></span></a>\n");
      out.write("\t");
 } 
      out.write('\n');
 } else if(name.equalsIgnoreCase("remove")) { 
      out.write('\n');
      out.write('	');
if(tooltip != null) { 
      out.write("\n");
      out.write("\t\t<a data-toggle=\"tooltip\" title=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tooltip}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\" style=\"padding-left:2px;cursor: pointer;\" onclick=\"javascript:loadProcess('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("');\"><span class=\"glyphicon glyphicon-minus-sign\" style=\"color:#016b8d;font-size:24px;\"></span></a>\n");
      out.write("\t");
} else { 
      out.write("\n");
      out.write("\t\t<a style=\"padding-left:2px;padding-left:2px;cursor: pointer;\" onclick=\"javascript:loadProcess('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("');\"><span class=\"glyphicon glyphicon-minus-sign\" style=\"color:#016b8d;font-size:24px;\"></span></a>\n");
      out.write("\t");
 } 
      out.write('\n');
 } else if(name.equalsIgnoreCase("print")) { 
      out.write("\n");
      out.write("\t<a style=\"padding-left:2px;cursor: pointer;\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\" target=\"_blank\"><span class=\"glyphicon glyphicon-print\" style=\"color:#016b8d;font-size:24px;\"></span></a>\n");
 } else if(name.equalsIgnoreCase("refresh")) { 
      out.write("\n");
      out.write("\t<a style=\"padding-left:2px;cursor: pointer;\" onclick=\"javascript:loadTab('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("');\"><span class=\"glyphicon glyphicon-refresh\" style=\"color:#016b8d;font-size:24px;\"></span></a>\n");
 } else if(name.equalsIgnoreCase("stage")) { 
      out.write("\n");
      out.write("\t<a style=\"padding-left:2px;cursor: pointer;\" onclick=\"javascript:loadTab('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("');\"><span class=\"glyphicon glyphicon-log-in\" style=\"color:#016b8d;font-size:24px;\"></span></a>\n");
 } else if(name.equalsIgnoreCase("checkout")) { 
      out.write("\n");
      out.write("\t<a style=\"padding-left:2px;cursor: pointer;\" onclick=\"javascript:loadTab('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("');\"><span class=\"glyphicon glyphicon-new-window\" style=\"color:#016b8d;font-size:24px;\"></span></a>\n");
 } else { 
      out.write('\n');
      out.write('	');
 if(process!=null && warning!=null) { 
      out.write("\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-primary btn-sm\" onclick=\"javascript:loadProcessWithWarning('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("',this,'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${warning}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("');\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("</button>\n");
      out.write("\t");
 } else if(process!=null) { 
      out.write("\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-primary btn-sm\" onclick=\"javascript:loadProcess('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("');\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("</button>\n");
      out.write("\t");
 } else if(newtab!=null) { 
      out.write("\n");
      out.write("\t\t<a class=\"btn btn-primary btn-sm\" style=\"cursor: pointer;\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\" target=\"_blank\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("</a>\n");
      out.write("\t");
 } else { 
      out.write("\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-primary btn-sm\" onclick=\"javascript:loadTab('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("');\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("</button>\n");
      out.write("\t");
 } 
      out.write('\n');
 } 
      out.write('\n');
    } catch( java.lang.Throwable t ) {
      if( t instanceof javax.servlet.jsp.SkipPageException )
          throw (javax.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof javax.servlet.jsp.JspException )
          throw (javax.servlet.jsp.JspException) t;
      throw new javax.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
    }
  }
}
