/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2016-09-20 18:33:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.trampoline.pick_005flists;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Enumeration;
import com.monumental.trampoline.component.*;
import com.monumental.trampoline.security.*;
import com.reeltrack.picklists.*;
import com.reeltrack.users.*;
import com.reeltrack.foremans.*;
import com.reeltrack.reels.*;

public final class archive_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(39);
    _jspx_dependants.put("/WEB-INF/tags/form/row_begin.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/admin/subtitle.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/select_end.tag", Long.valueOf(1472002170000L));
    _jspx_dependants.put("/WEB-INF/tags/form/submit_inline.tag", Long.valueOf(1472425523000L));
    _jspx_dependants.put("/WEB-INF/tags/listing/row_end.tag", Long.valueOf(1472002170000L));
    _jspx_dependants.put("/WEB-INF/tags/admin/title.tag", Long.valueOf(1472493852000L));
    _jspx_dependants.put("/WEB-INF/tags/listing/end.tag", Long.valueOf(1472002170000L));
    _jspx_dependants.put("/WEB-INF/tags/admin/set_tabset.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/trampoline/pick_lists/../common/includes/only_users.jsp", Long.valueOf(1472002170000L));
    _jspx_dependants.put("/WEB-INF/tags/form/textfield.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/admin/box_end.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/buttonset_end.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/html/end.tag", Long.valueOf(1472002193000L));
    _jspx_dependants.put("/WEB-INF/tags/listing/cell_begin.tag", Long.valueOf(1472002193000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1472002170000L));
    _jspx_dependants.put("/WEB-INF/tags/admin/box_begin.tag", Long.valueOf(1472498302000L));
    _jspx_dependants.put("/WEB-INF/tags/form/select_begin.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/linkbutton.tag", Long.valueOf(1472521293000L));
    _jspx_dependants.put("/WEB-INF/tags/listing/header_begin.tag", Long.valueOf(1472002193000L));
    _jspx_dependants.put("/WEB-INF/tags/form/content_begin.tag", Long.valueOf(1472496815000L));
    _jspx_dependants.put("/WEB-INF/tags/form/content_end.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/option.tag", Long.valueOf(1472002170000L));
    _jspx_dependants.put("/WEB-INF/tags/listing/row_begin.tag", Long.valueOf(1472002193000L));
    _jspx_dependants.put("/WEB-INF/tags/listing/begin.tag", Long.valueOf(1472002193000L));
    _jspx_dependants.put("/WEB-INF/tags/listing/header_end.tag", Long.valueOf(1472002193000L));
    _jspx_dependants.put("jar:file:/www/new/tomcat/webapps/../../web/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098725490000L));
    _jspx_dependants.put("/WEB-INF/tags/html/begin.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/begin_selfsubmit.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/label.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("jar:file:/www/new/tomcat/webapps/../../web/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098725490000L));
    _jspx_dependants.put("/WEB-INF/tags/form/clearform_inline.tag", Long.valueOf(1472422507000L));
    _jspx_dependants.put("/WEB-INF/tags/form/end.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/listing/header_cell.tag", Long.valueOf(1472002193000L));
    _jspx_dependants.put("/WEB-INF/tags/form/label_inline.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/end_inline.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/row_end.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/listing/cell_end.tag", Long.valueOf(1472002170000L));
    _jspx_dependants.put("/WEB-INF/tags/form/begin_selfsubmit_inline.tag", Long.valueOf(1472002192000L));
    _jspx_dependants.put("/WEB-INF/tags/form/buttonset_begin.tag", Long.valueOf(1472002192000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\n");
      com.reeltrack.users.RTUserLoginMgr onlyuserLoginMgr = null;
      onlyuserLoginMgr = (com.reeltrack.users.RTUserLoginMgr) _jspx_page_context.getAttribute("onlyuserLoginMgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (onlyuserLoginMgr == null){
        onlyuserLoginMgr = new com.reeltrack.users.RTUserLoginMgr();
        _jspx_page_context.setAttribute("onlyuserLoginMgr", onlyuserLoginMgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
      out.write('\n');
 onlyuserLoginMgr.init(pageContext); 
      out.write('\n');
      out.write('\n');
 if(!onlyuserLoginMgr.isLoggedIn()) { 
      out.write("\n");
      out.write("\t<script type=\"text/javascript\" language=\"javascript\">\n");
      out.write("\t\t\t// first, if we're in the _submissionFrame, call window location on the parent\n");
      out.write("\t\t\tparent.window.location = \"");
      out.print( request.getContextPath() );
      out.write("/trampoline/index.jsp\";\n");
      out.write("\t\n");
      out.write("\t\t\t// otherwise, we'll be doing this on this window\n");
      out.write("\t\t\twindow.location = \"");
      out.print( request.getContextPath() );
      out.write("/trampoline/index.jsp\";\n");
      out.write("\t</script>\n");
 } 
      out.write('\n');
 if(!onlyuserLoginMgr.isLoggedIn()) return; 
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      com.monumental.trampoline.datasources.DbResources dbResources = null;
      dbResources = (com.monumental.trampoline.datasources.DbResources) _jspx_page_context.getAttribute("dbResources", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (dbResources == null){
        dbResources = new com.monumental.trampoline.datasources.DbResources();
        _jspx_page_context.setAttribute("dbResources", dbResources, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
      com.reeltrack.users.RTUserLoginMgr userLoginMgr = null;
      userLoginMgr = (com.reeltrack.users.RTUserLoginMgr) _jspx_page_context.getAttribute("userLoginMgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (userLoginMgr == null){
        userLoginMgr = new com.reeltrack.users.RTUserLoginMgr();
        _jspx_page_context.setAttribute("userLoginMgr", userLoginMgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
      com.reeltrack.picklists.PickListMgr picklistMgr = null;
      picklistMgr = (com.reeltrack.picklists.PickListMgr) _jspx_page_context.getAttribute("picklistMgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (picklistMgr == null){
        picklistMgr = new com.reeltrack.picklists.PickListMgr();
        _jspx_page_context.setAttribute("picklistMgr", picklistMgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
      com.reeltrack.foremans.ForemanMgr foremanMgr = null;
      foremanMgr = (com.reeltrack.foremans.ForemanMgr) _jspx_page_context.getAttribute("foremanMgr", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (foremanMgr == null){
        foremanMgr = new com.reeltrack.foremans.ForemanMgr();
        _jspx_page_context.setAttribute("foremanMgr", foremanMgr, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');
      out.write('\n');
 userLoginMgr.init(pageContext); 
      out.write('\n');
 picklistMgr.init(pageContext,dbResources); 
      out.write('\n');
 foremanMgr.init(pageContext,dbResources); 
      out.write('\n');

RTUser user = (RTUser)userLoginMgr.getUser();

int howMany = 25;
int pageNdx = 1;
if(request.getParameter("pageIdx") != null) {
    pageNdx = Integer.parseInt(request.getParameter("pageIdx"));
}

int skip = (pageNdx-1) * howMany;
if(request.getParameter("skip") != null) {
    skip = Integer.parseInt(request.getParameter("skip"));
}

PickList content = new PickList();
Reel reel = new Reel();
ReelCircuit circuit = new ReelCircuit();
if(session.getAttribute("pick_lists_search")!=null) {
    content = (PickList)session.getAttribute("pick_lists_search");
}
if(session.getAttribute("pick_lists_search_reel")!=null) {
    reel = (Reel)session.getAttribute("pick_lists_search_reel");
}
if(session.getAttribute("pick_lists_search_circuit")!=null) {
    circuit = (ReelCircuit)session.getAttribute("pick_lists_search_circuit");
}

if(request.getParameter(PickList.ID_COLUMN) != null) {
	if(!request.getParameter(PickList.ID_COLUMN).equals("")) {
		content.setId(Integer.parseInt(request.getParameter(PickList.ID_COLUMN)));
	} else {
		content.getData().removeValue(PickList.ID_COLUMN);
	}
}

if(request.getParameter(PickList.FOREMAN_COLUMN) != null) {
    content.setForeman(request.getParameter(PickList.FOREMAN_COLUMN));
}

if(request.getParameter(Reel.REEL_TAG_COLUMN) != null) {
    reel.setReelTag(request.getParameter(Reel.REEL_TAG_COLUMN));
    reel.setSearchOp(Reel.REEL_TAG_COLUMN, Reel.TRUE_PARTIAL);
}

if(request.getParameter(Reel.CABLE_DESCRIPTION_COLUMN) != null) {
    reel.setCableDescription(request.getParameter(Reel.CABLE_DESCRIPTION_COLUMN));
    reel.setSearchOp(Reel.CABLE_DESCRIPTION_COLUMN, Reel.TRUE_PARTIAL);
}

if(request.getParameter(Reel.CUSTOMER_PN_COLUMN) != null) {
    reel.setCustomerPN(request.getParameter(Reel.CUSTOMER_PN_COLUMN));
    reel.setSearchOp(Reel.CUSTOMER_PN_COLUMN, Reel.PARTIAL);
}

if(request.getParameter(ReelCircuit.PARAM) != null) {
    circuit.setId(Integer.parseInt(request.getParameter(ReelCircuit.PARAM)));
}

if(request.getParameter(Reel.CR_ID_COLUMN) != null) {
    if(request.getParameter(Reel.CR_ID_COLUMN).equals("")) {
        reel.getData().removeValue(Reel.CR_ID_COLUMN);
    } else {
        reel.setCrId(Integer.parseInt(request.getParameter(Reel.CR_ID_COLUMN)));
        reel.setSearchOp(Reel.CR_ID_COLUMN, Reel.EQ);
    }
}

session.setAttribute("pick_lists_search",content);
session.setAttribute("pick_lists_search_reel",reel);
session.setAttribute("pick_lists_search_circuit",circuit);

CompEntities contents = picklistMgr.getPickListsArchive(content, reel, circuit);

Foreman foreman = new Foreman();
foreman.setCustomerId(user.getCustomerId());
CompEntities foremans = foremanMgr.searchForeman(foreman, Foreman.NAME_COLUMN, true);

CompEntities circuits = picklistMgr.getReelCircuits();

boolean dosearch = true;
String tempURL = "";

      out.write('\n');
      out.write('\n');
 dbResources.close(); 
      out.write('\n');
      if (_jspx_meth_html_005fbegin_005f0(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_admin_005ftitle_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_admin_005fsubtitle_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_admin_005fbox_005fbegin_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_form_005fbegin_005fselfsubmit_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");

        if(content.getId()!=0) {
            tempURL = new Integer(content.getId()).toString();
        } else {
            tempURL = "";
        }
        
      out.write("\n");
      out.write("        ");
      //  form:textfield
      org.apache.jsp.tag.webform.textfield_tag _jspx_th_form_005ftextfield_005f0 = (new org.apache.jsp.tag.webform.textfield_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005ftextfield_005f0);
      _jspx_th_form_005ftextfield_005f0.setJspContext(_jspx_page_context);
      // /trampoline/pick_lists/archive.jsp(125,8) name = pixelwidth type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f0.setPixelwidth("40");
      // /trampoline/pick_lists/archive.jsp(125,8) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f0.setLabel("ID:");
      // /trampoline/pick_lists/archive.jsp(125,8) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f0.setName( PickList.ID_COLUMN );
      // /trampoline/pick_lists/archive.jsp(125,8) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f0.setValue( tempURL );
      _jspx_th_form_005ftextfield_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005ftextfield_005f0);
      out.write("\n");
      out.write("        ");
 if(reel.getCrId()!=0) { 
      out.write("\n");
      out.write("\t\t\t");
      //  form:textfield
      org.apache.jsp.tag.webform.textfield_tag _jspx_th_form_005ftextfield_005f1 = (new org.apache.jsp.tag.webform.textfield_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005ftextfield_005f1);
      _jspx_th_form_005ftextfield_005f1.setJspContext(_jspx_page_context);
      // /trampoline/pick_lists/archive.jsp(127,3) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f1.setLabel("CRID #:");
      // /trampoline/pick_lists/archive.jsp(127,3) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f1.setName( Reel.CR_ID_COLUMN );
      // /trampoline/pick_lists/archive.jsp(127,3) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f1.setValue( new Integer(reel.getCrId()).toString() );
      _jspx_th_form_005ftextfield_005f1.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005ftextfield_005f1);
      out.write('\n');
      out.write('	');
      out.write('	');
 } else { 
      out.write("\n");
      out.write("\t\t\t");
      //  form:textfield
      org.apache.jsp.tag.webform.textfield_tag _jspx_th_form_005ftextfield_005f2 = (new org.apache.jsp.tag.webform.textfield_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005ftextfield_005f2);
      _jspx_th_form_005ftextfield_005f2.setJspContext(_jspx_page_context);
      // /trampoline/pick_lists/archive.jsp(129,3) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f2.setLabel("CRID #:");
      // /trampoline/pick_lists/archive.jsp(129,3) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f2.setName( Reel.CR_ID_COLUMN );
      // /trampoline/pick_lists/archive.jsp(129,3) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f2.setValue("");
      _jspx_th_form_005ftextfield_005f2.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005ftextfield_005f2);
      out.write('\n');
      out.write('	');
      out.write('	');
 } 
      out.write('\n');
      out.write('	');
      out.write('	');
      //  form:textfield
      org.apache.jsp.tag.webform.textfield_tag _jspx_th_form_005ftextfield_005f3 = (new org.apache.jsp.tag.webform.textfield_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005ftextfield_005f3);
      _jspx_th_form_005ftextfield_005f3.setJspContext(_jspx_page_context);
      // /trampoline/pick_lists/archive.jsp(131,2) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f3.setLabel("Reel Tag:");
      // /trampoline/pick_lists/archive.jsp(131,2) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f3.setName( Reel.REEL_TAG_COLUMN );
      // /trampoline/pick_lists/archive.jsp(131,2) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f3.setValue( reel.getReelTag() );
      _jspx_th_form_005ftextfield_005f3.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005ftextfield_005f3);
      out.write("\n");
      out.write("        ");
      //  form:textfield
      org.apache.jsp.tag.webform.textfield_tag _jspx_th_form_005ftextfield_005f4 = (new org.apache.jsp.tag.webform.textfield_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005ftextfield_005f4);
      _jspx_th_form_005ftextfield_005f4.setJspContext(_jspx_page_context);
      // /trampoline/pick_lists/archive.jsp(132,8) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f4.setLabel("Description:");
      // /trampoline/pick_lists/archive.jsp(132,8) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f4.setName( Reel.CABLE_DESCRIPTION_COLUMN );
      // /trampoline/pick_lists/archive.jsp(132,8) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f4.setValue( reel.getCableDescription() );
      _jspx_th_form_005ftextfield_005f4.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005ftextfield_005f4);
      out.write("\n");
      out.write("        ");
 tempURL = user.getCustomerName() + " P/N:"; 
      out.write("\n");
      out.write("        ");
      //  form:textfield
      org.apache.jsp.tag.webform.textfield_tag _jspx_th_form_005ftextfield_005f5 = (new org.apache.jsp.tag.webform.textfield_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005ftextfield_005f5);
      _jspx_th_form_005ftextfield_005f5.setJspContext(_jspx_page_context);
      // /trampoline/pick_lists/archive.jsp(134,8) name = label type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f5.setLabel( tempURL );
      // /trampoline/pick_lists/archive.jsp(134,8) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f5.setName( Reel.CUSTOMER_PN_COLUMN );
      // /trampoline/pick_lists/archive.jsp(134,8) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005ftextfield_005f5.setValue( reel.getCustomerPN() );
      _jspx_th_form_005ftextfield_005f5.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005ftextfield_005f5);
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_form_005frow_005fbegin_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_form_005flabel_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_form_005fcontent_005fbegin_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      //  form:select_begin
      org.apache.jsp.tag.webform.select_005fbegin_tag _jspx_th_form_005fselect_005fbegin_005f0 = (new org.apache.jsp.tag.webform.select_005fbegin_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005fselect_005fbegin_005f0);
      _jspx_th_form_005fselect_005fbegin_005f0.setJspContext(_jspx_page_context);
      // /trampoline/pick_lists/archive.jsp(138,12) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fselect_005fbegin_005f0.setName( ReelCircuit.PARAM );
      _jspx_th_form_005fselect_005fbegin_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005fselect_005fbegin_005f0);
      out.write("\n");
      out.write("                ");
      //  form:option
      org.apache.jsp.tag.webform.option_tag _jspx_th_form_005foption_005f0 = (new org.apache.jsp.tag.webform.option_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005foption_005f0);
      _jspx_th_form_005foption_005f0.setJspContext(_jspx_page_context);
      // /trampoline/pick_lists/archive.jsp(139,16) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005foption_005f0.setName("Any");
      // /trampoline/pick_lists/archive.jsp(139,16) name = value type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005foption_005f0.setValue("0");
      // /trampoline/pick_lists/archive.jsp(139,16) name = match type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005foption_005f0.setMatch( new Integer(circuit.getId()).toString() );
      _jspx_th_form_005foption_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005foption_005f0);
      out.write("\n");
      out.write("                ");
 for(int c=0; c<circuits.howMany(); c++) { 
      out.write("\n");
      out.write("                    ");
 ReelCircuit tmpCircuit = (ReelCircuit)circuits.get(c); 
      out.write("\n");
      out.write("                    ");
      //  form:option
      org.apache.jsp.tag.webform.option_tag _jspx_th_form_005foption_005f1 = (new org.apache.jsp.tag.webform.option_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005foption_005f1);
      _jspx_th_form_005foption_005f1.setJspContext(_jspx_page_context);
      // /trampoline/pick_lists/archive.jsp(142,20) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005foption_005f1.setName( tmpCircuit.getName() );
      // /trampoline/pick_lists/archive.jsp(142,20) name = value type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005foption_005f1.setValue( new Integer(tmpCircuit.getId()).toString() );
      // /trampoline/pick_lists/archive.jsp(142,20) name = match type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005foption_005f1.setMatch( new Integer(circuit.getId()).toString() );
      _jspx_th_form_005foption_005f1.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005foption_005f1);
      out.write("\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_form_005fselect_005fend_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_form_005fcontent_005fend_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_form_005frow_005fend_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_form_005frow_005fbegin_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_form_005flabel_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_form_005fcontent_005fbegin_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      //  form:select_begin
      org.apache.jsp.tag.webform.select_005fbegin_tag _jspx_th_form_005fselect_005fbegin_005f1 = (new org.apache.jsp.tag.webform.select_005fbegin_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005fselect_005fbegin_005f1);
      _jspx_th_form_005fselect_005fbegin_005f1.setJspContext(_jspx_page_context);
      // /trampoline/pick_lists/archive.jsp(150,12) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005fselect_005fbegin_005f1.setName( PickList.FOREMAN_COLUMN );
      _jspx_th_form_005fselect_005fbegin_005f1.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005fselect_005fbegin_005f1);
      out.write("\n");
      out.write("                ");
      //  form:option
      org.apache.jsp.tag.webform.option_tag _jspx_th_form_005foption_005f2 = (new org.apache.jsp.tag.webform.option_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005foption_005f2);
      _jspx_th_form_005foption_005f2.setJspContext(_jspx_page_context);
      // /trampoline/pick_lists/archive.jsp(151,16) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005foption_005f2.setName("Any");
      // /trampoline/pick_lists/archive.jsp(151,16) name = value type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005foption_005f2.setValue("");
      // /trampoline/pick_lists/archive.jsp(151,16) name = match type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005foption_005f2.setMatch( content.getForeman() );
      _jspx_th_form_005foption_005f2.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005foption_005f2);
      out.write("\n");
      out.write("                ");
 for(int f=0; f<foremans.howMany(); f++) { 
      out.write("\n");
      out.write("                    ");
 foreman = (Foreman)foremans.get(f); 
      out.write("\n");
      out.write("                    ");
      //  form:option
      org.apache.jsp.tag.webform.option_tag _jspx_th_form_005foption_005f3 = (new org.apache.jsp.tag.webform.option_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005foption_005f3);
      _jspx_th_form_005foption_005f3.setJspContext(_jspx_page_context);
      // /trampoline/pick_lists/archive.jsp(154,20) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005foption_005f3.setName( foreman.getName() );
      // /trampoline/pick_lists/archive.jsp(154,20) name = value type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005foption_005f3.setValue( foreman.getName() );
      // /trampoline/pick_lists/archive.jsp(154,20) name = match type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005foption_005f3.setMatch( content.getForeman() );
      _jspx_th_form_005foption_005f3.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005foption_005f3);
      out.write("\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_form_005fselect_005fend_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_form_005fcontent_005fend_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_form_005frow_005fend_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_form_005frow_005fbegin_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_form_005flabel_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_form_005fbuttonset_005fbegin_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                ");
      if (_jspx_meth_form_005fsubmit_005finline_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                ");
      if (_jspx_meth_form_005fclearform_005finline_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_form_005fbuttonset_005fend_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_form_005frow_005fend_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_form_005fend_005f0(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_admin_005fbox_005fend_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_admin_005fsubtitle_005f1(_jspx_page_context))
        return;
      out.write('\n');
 if(dosearch) { 
      out.write("\n");
      out.write("    ");
 if(contents.howMany() > 0) { 
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_admin_005fbox_005fbegin_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_listing_005fbegin_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_listing_005fheader_005fbegin_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fheader_005fcell_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fheader_005fcell_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fheader_005fcell_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fheader_005fcell_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fheader_005fcell_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fheader_005fcell_005f5(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_listing_005fheader_005fend_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
 for(int i=0; i<contents.howMany(); i++) { 
      out.write("\n");
      out.write("        ");
 content = (PickList)contents.get(i); 
      out.write("\n");
      out.write("        ");
      //  listing:row_begin
      org.apache.jsp.tag.weblisting.row_005fbegin_tag _jspx_th_listing_005frow_005fbegin_005f0 = (new org.apache.jsp.tag.weblisting.row_005fbegin_tag());
      _jsp_instancemanager.newInstance(_jspx_th_listing_005frow_005fbegin_005f0);
      _jspx_th_listing_005frow_005fbegin_005f0.setJspContext(_jspx_page_context);
      // /trampoline/pick_lists/archive.jsp(196,8) name = row type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_listing_005frow_005fbegin_005f0.setRow( new Integer(i).toString() );
      _jspx_th_listing_005frow_005fbegin_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_listing_005frow_005fbegin_005f0);
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fcell_005fbegin_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                ");
      out.print( content.getCreatedDateText() );
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fcell_005fend_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fcell_005fbegin_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                ");
      out.print( content.getName() );
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fcell_005fend_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fcell_005fbegin_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                ");
      out.print( content.getForeman() );
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fcell_005fend_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fcell_005fbegin_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                ");

                CompEntities reels = content.getCompEntities(Reel.PARAM);
                int total = 0;
                int staged = 0;
                int checkedout = 0;
                if(reels!=null) {
                    for(int y=0; y<reels.howMany();y++) {
                        Reel reelnum = (Reel)reels.get(y);
                        total++;
                        if(reelnum.getStatus().equals(Reel.STATUS_STAGED)) staged++;
                        if(reelnum.getStatus().equals(Reel.STATUS_CHECKED_OUT)) checkedout++;
                    }
                }
                
      out.write("\n");
      out.write("                ");
 tempURL = new Integer(total).toString() + "/" + new Integer(staged).toString() + "/" + new Integer(checkedout).toString(); 
      out.write("\n");
      out.write("                ");
      out.print( tempURL );
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fcell_005fend_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fcell_005fbegin_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                ");
      out.print( content.getStatus() );
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fcell_005fend_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fcell_005fbegin_005f5(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                ");
 tempURL = "pick_lists/edit.jsp?" +  PickList.PARAM + "=" + content.getId(); 
      out.write("\n");
      out.write("                ");
      //  form:linkbutton
      org.apache.jsp.tag.webform.linkbutton_tag _jspx_th_form_005flinkbutton_005f0 = (new org.apache.jsp.tag.webform.linkbutton_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005flinkbutton_005f0);
      _jspx_th_form_005flinkbutton_005f0.setJspContext(_jspx_page_context);
      // /trampoline/pick_lists/archive.jsp(229,16) name = url type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005flinkbutton_005f0.setUrl( tempURL );
      // /trampoline/pick_lists/archive.jsp(229,16) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005flinkbutton_005f0.setName("EDIT");
      _jspx_th_form_005flinkbutton_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005flinkbutton_005f0);
      out.write("\n");
      out.write("                ");
      out.write("\n");
      out.write("                ");
 tempURL = "pick_lists/picklist.jsp?" + PickList.PARAM + "=" + content.getId(); 
      out.write("\n");
      out.write("                ");
      out.write("\n");
      out.write("                ");
      //  form:linkbutton
      org.apache.jsp.tag.webform.linkbutton_tag _jspx_th_form_005flinkbutton_005f1 = (new org.apache.jsp.tag.webform.linkbutton_tag());
      _jsp_instancemanager.newInstance(_jspx_th_form_005flinkbutton_005f1);
      _jspx_th_form_005flinkbutton_005f1.setJspContext(_jspx_page_context);
      // /trampoline/pick_lists/archive.jsp(236,16) name = url type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005flinkbutton_005f1.setUrl( tempURL );
      // /trampoline/pick_lists/archive.jsp(236,16) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005flinkbutton_005f1.setName("PRINT");
      // /trampoline/pick_lists/archive.jsp(236,16) name = newtab type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_form_005flinkbutton_005f1.setNewtab("true");
      _jspx_th_form_005flinkbutton_005f1.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_form_005flinkbutton_005f1);
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_listing_005fcell_005fend_005f5(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_listing_005frow_005fend_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_listing_005fend_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_admin_005fbox_005fend_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_admin_005fsubtitle_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
 } 
      out.write('\n');
 } 
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_admin_005fset_005ftabset_005f0(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_html_005fend_005f0(_jspx_page_context))
        return;
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_html_005fbegin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:begin
    org.apache.jsp.tag.webhtml.begin_tag _jspx_th_html_005fbegin_005f0 = (new org.apache.jsp.tag.webhtml.begin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_html_005fbegin_005f0);
    _jspx_th_html_005fbegin_005f0.setJspContext(_jspx_page_context);
    _jspx_th_html_005fbegin_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_html_005fbegin_005f0);
    return false;
  }

  private boolean _jspx_meth_admin_005ftitle_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:title
    org.apache.jsp.tag.webadmin.title_tag _jspx_th_admin_005ftitle_005f0 = (new org.apache.jsp.tag.webadmin.title_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005ftitle_005f0);
    _jspx_th_admin_005ftitle_005f0.setJspContext(_jspx_page_context);
    // /trampoline/pick_lists/archive.jsp(113,0) name = heading type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005ftitle_005f0.setHeading("Pick Lists");
    // /trampoline/pick_lists/archive.jsp(113,0) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005ftitle_005f0.setText("Archive");
    _jspx_th_admin_005ftitle_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005ftitle_005f0);
    return false;
  }

  private boolean _jspx_meth_admin_005fsubtitle_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:subtitle
    org.apache.jsp.tag.webadmin.subtitle_tag _jspx_th_admin_005fsubtitle_005f0 = (new org.apache.jsp.tag.webadmin.subtitle_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fsubtitle_005f0);
    _jspx_th_admin_005fsubtitle_005f0.setJspContext(_jspx_page_context);
    // /trampoline/pick_lists/archive.jsp(115,0) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fsubtitle_005f0.setText("Filter Pick Lists");
    _jspx_th_admin_005fsubtitle_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fsubtitle_005f0);
    return false;
  }

  private boolean _jspx_meth_admin_005fbox_005fbegin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:box_begin
    org.apache.jsp.tag.webadmin.box_005fbegin_tag _jspx_th_admin_005fbox_005fbegin_005f0 = (new org.apache.jsp.tag.webadmin.box_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fbox_005fbegin_005f0);
    _jspx_th_admin_005fbox_005fbegin_005f0.setJspContext(_jspx_page_context);
    // /trampoline/pick_lists/archive.jsp(116,4) name = text type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fbox_005fbegin_005f0.setText("Filter Pick Lists");
    // /trampoline/pick_lists/archive.jsp(116,4) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fbox_005fbegin_005f0.setName("Filter_Pick_Lists");
    // /trampoline/pick_lists/archive.jsp(116,4) name = open type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fbox_005fbegin_005f0.setOpen("false");
    _jspx_th_admin_005fbox_005fbegin_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fbox_005fbegin_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005fbegin_005fselfsubmit_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:begin_selfsubmit
    org.apache.jsp.tag.webform.begin_005fselfsubmit_tag _jspx_th_form_005fbegin_005fselfsubmit_005f0 = (new org.apache.jsp.tag.webform.begin_005fselfsubmit_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fbegin_005fselfsubmit_005f0);
    _jspx_th_form_005fbegin_005fselfsubmit_005f0.setJspContext(_jspx_page_context);
    // /trampoline/pick_lists/archive.jsp(117,4) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fbegin_005fselfsubmit_005f0.setName("search");
    // /trampoline/pick_lists/archive.jsp(117,4) name = action type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fbegin_005fselfsubmit_005f0.setAction("pick_lists/search.jsp");
    _jspx_th_form_005fbegin_005fselfsubmit_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fbegin_005fselfsubmit_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005frow_005fbegin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:row_begin
    org.apache.jsp.tag.webform.row_005fbegin_tag _jspx_th_form_005frow_005fbegin_005f0 = (new org.apache.jsp.tag.webform.row_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005frow_005fbegin_005f0);
    _jspx_th_form_005frow_005fbegin_005f0.setJspContext(_jspx_page_context);
    _jspx_th_form_005frow_005fbegin_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005frow_005fbegin_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005flabel_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:label
    org.apache.jsp.tag.webform.label_tag _jspx_th_form_005flabel_005f0 = (new org.apache.jsp.tag.webform.label_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005flabel_005f0);
    _jspx_th_form_005flabel_005f0.setJspContext(_jspx_page_context);
    // /trampoline/pick_lists/archive.jsp(136,12) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005flabel_005f0.setName("");
    // /trampoline/pick_lists/archive.jsp(136,12) name = label type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005flabel_005f0.setLabel("Circuit:");
    _jspx_th_form_005flabel_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005flabel_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005fcontent_005fbegin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:content_begin
    org.apache.jsp.tag.webform.content_005fbegin_tag _jspx_th_form_005fcontent_005fbegin_005f0 = (new org.apache.jsp.tag.webform.content_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fcontent_005fbegin_005f0);
    _jspx_th_form_005fcontent_005fbegin_005f0.setJspContext(_jspx_page_context);
    _jspx_th_form_005fcontent_005fbegin_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fcontent_005fbegin_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005fselect_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:select_end
    org.apache.jsp.tag.webform.select_005fend_tag _jspx_th_form_005fselect_005fend_005f0 = (new org.apache.jsp.tag.webform.select_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fselect_005fend_005f0);
    _jspx_th_form_005fselect_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_form_005fselect_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fselect_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005fcontent_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:content_end
    org.apache.jsp.tag.webform.content_005fend_tag _jspx_th_form_005fcontent_005fend_005f0 = (new org.apache.jsp.tag.webform.content_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fcontent_005fend_005f0);
    _jspx_th_form_005fcontent_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_form_005fcontent_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fcontent_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005frow_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:row_end
    org.apache.jsp.tag.webform.row_005fend_tag _jspx_th_form_005frow_005fend_005f0 = (new org.apache.jsp.tag.webform.row_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005frow_005fend_005f0);
    _jspx_th_form_005frow_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_form_005frow_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005frow_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005frow_005fbegin_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:row_begin
    org.apache.jsp.tag.webform.row_005fbegin_tag _jspx_th_form_005frow_005fbegin_005f1 = (new org.apache.jsp.tag.webform.row_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005frow_005fbegin_005f1);
    _jspx_th_form_005frow_005fbegin_005f1.setJspContext(_jspx_page_context);
    _jspx_th_form_005frow_005fbegin_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005frow_005fbegin_005f1);
    return false;
  }

  private boolean _jspx_meth_form_005flabel_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:label
    org.apache.jsp.tag.webform.label_tag _jspx_th_form_005flabel_005f1 = (new org.apache.jsp.tag.webform.label_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005flabel_005f1);
    _jspx_th_form_005flabel_005f1.setJspContext(_jspx_page_context);
    // /trampoline/pick_lists/archive.jsp(148,12) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005flabel_005f1.setName("");
    // /trampoline/pick_lists/archive.jsp(148,12) name = label type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005flabel_005f1.setLabel("Foreman:");
    _jspx_th_form_005flabel_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005flabel_005f1);
    return false;
  }

  private boolean _jspx_meth_form_005fcontent_005fbegin_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:content_begin
    org.apache.jsp.tag.webform.content_005fbegin_tag _jspx_th_form_005fcontent_005fbegin_005f1 = (new org.apache.jsp.tag.webform.content_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fcontent_005fbegin_005f1);
    _jspx_th_form_005fcontent_005fbegin_005f1.setJspContext(_jspx_page_context);
    _jspx_th_form_005fcontent_005fbegin_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fcontent_005fbegin_005f1);
    return false;
  }

  private boolean _jspx_meth_form_005fselect_005fend_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:select_end
    org.apache.jsp.tag.webform.select_005fend_tag _jspx_th_form_005fselect_005fend_005f1 = (new org.apache.jsp.tag.webform.select_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fselect_005fend_005f1);
    _jspx_th_form_005fselect_005fend_005f1.setJspContext(_jspx_page_context);
    _jspx_th_form_005fselect_005fend_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fselect_005fend_005f1);
    return false;
  }

  private boolean _jspx_meth_form_005fcontent_005fend_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:content_end
    org.apache.jsp.tag.webform.content_005fend_tag _jspx_th_form_005fcontent_005fend_005f1 = (new org.apache.jsp.tag.webform.content_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fcontent_005fend_005f1);
    _jspx_th_form_005fcontent_005fend_005f1.setJspContext(_jspx_page_context);
    _jspx_th_form_005fcontent_005fend_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fcontent_005fend_005f1);
    return false;
  }

  private boolean _jspx_meth_form_005frow_005fend_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:row_end
    org.apache.jsp.tag.webform.row_005fend_tag _jspx_th_form_005frow_005fend_005f1 = (new org.apache.jsp.tag.webform.row_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005frow_005fend_005f1);
    _jspx_th_form_005frow_005fend_005f1.setJspContext(_jspx_page_context);
    _jspx_th_form_005frow_005fend_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005frow_005fend_005f1);
    return false;
  }

  private boolean _jspx_meth_form_005frow_005fbegin_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:row_begin
    org.apache.jsp.tag.webform.row_005fbegin_tag _jspx_th_form_005frow_005fbegin_005f2 = (new org.apache.jsp.tag.webform.row_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005frow_005fbegin_005f2);
    _jspx_th_form_005frow_005fbegin_005f2.setJspContext(_jspx_page_context);
    _jspx_th_form_005frow_005fbegin_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005frow_005fbegin_005f2);
    return false;
  }

  private boolean _jspx_meth_form_005flabel_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:label
    org.apache.jsp.tag.webform.label_tag _jspx_th_form_005flabel_005f2 = (new org.apache.jsp.tag.webform.label_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005flabel_005f2);
    _jspx_th_form_005flabel_005f2.setJspContext(_jspx_page_context);
    // /trampoline/pick_lists/archive.jsp(160,12) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005flabel_005f2.setName("");
    // /trampoline/pick_lists/archive.jsp(160,12) name = label type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005flabel_005f2.setLabel("");
    _jspx_th_form_005flabel_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005flabel_005f2);
    return false;
  }

  private boolean _jspx_meth_form_005fbuttonset_005fbegin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:buttonset_begin
    org.apache.jsp.tag.webform.buttonset_005fbegin_tag _jspx_th_form_005fbuttonset_005fbegin_005f0 = (new org.apache.jsp.tag.webform.buttonset_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fbuttonset_005fbegin_005f0);
    _jspx_th_form_005fbuttonset_005fbegin_005f0.setJspContext(_jspx_page_context);
    // /trampoline/pick_lists/archive.jsp(161,12) name = align type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fbuttonset_005fbegin_005f0.setAlign("left");
    // /trampoline/pick_lists/archive.jsp(161,12) name = padding type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fbuttonset_005fbegin_005f0.setPadding("0");
    _jspx_th_form_005fbuttonset_005fbegin_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fbuttonset_005fbegin_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005fsubmit_005finline_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:submit_inline
    org.apache.jsp.tag.webform.submit_005finline_tag _jspx_th_form_005fsubmit_005finline_005f0 = (new org.apache.jsp.tag.webform.submit_005finline_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fsubmit_005finline_005f0);
    _jspx_th_form_005fsubmit_005finline_005f0.setJspContext(_jspx_page_context);
    // /trampoline/pick_lists/archive.jsp(162,16) name = button type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f0.setButton("submit");
    // /trampoline/pick_lists/archive.jsp(162,16) name = waiting type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f0.setWaiting("true");
    // /trampoline/pick_lists/archive.jsp(162,16) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f0.setName("search");
    // /trampoline/pick_lists/archive.jsp(162,16) name = action type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fsubmit_005finline_005f0.setAction("test");
    _jspx_th_form_005fsubmit_005finline_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fsubmit_005finline_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005fclearform_005finline_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:clearform_inline
    org.apache.jsp.tag.webform.clearform_005finline_tag _jspx_th_form_005fclearform_005finline_005f0 = (new org.apache.jsp.tag.webform.clearform_005finline_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fclearform_005finline_005f0);
    _jspx_th_form_005fclearform_005finline_005f0.setJspContext(_jspx_page_context);
    // /trampoline/pick_lists/archive.jsp(163,16) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_form_005fclearform_005finline_005f0.setName("search");
    _jspx_th_form_005fclearform_005finline_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fclearform_005finline_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005fbuttonset_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:buttonset_end
    org.apache.jsp.tag.webform.buttonset_005fend_tag _jspx_th_form_005fbuttonset_005fend_005f0 = (new org.apache.jsp.tag.webform.buttonset_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fbuttonset_005fend_005f0);
    _jspx_th_form_005fbuttonset_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_form_005fbuttonset_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fbuttonset_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005frow_005fend_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:row_end
    org.apache.jsp.tag.webform.row_005fend_tag _jspx_th_form_005frow_005fend_005f2 = (new org.apache.jsp.tag.webform.row_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005frow_005fend_005f2);
    _jspx_th_form_005frow_005fend_005f2.setJspContext(_jspx_page_context);
    _jspx_th_form_005frow_005fend_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005frow_005fend_005f2);
    return false;
  }

  private boolean _jspx_meth_form_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:end
    org.apache.jsp.tag.webform.end_tag _jspx_th_form_005fend_005f0 = (new org.apache.jsp.tag.webform.end_tag());
    _jsp_instancemanager.newInstance(_jspx_th_form_005fend_005f0);
    _jspx_th_form_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_form_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_form_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_admin_005fbox_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:box_end
    org.apache.jsp.tag.webadmin.box_005fend_tag _jspx_th_admin_005fbox_005fend_005f0 = (new org.apache.jsp.tag.webadmin.box_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fbox_005fend_005f0);
    _jspx_th_admin_005fbox_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_admin_005fbox_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fbox_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_admin_005fsubtitle_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:subtitle
    org.apache.jsp.tag.webadmin.subtitle_tag _jspx_th_admin_005fsubtitle_005f1 = (new org.apache.jsp.tag.webadmin.subtitle_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fsubtitle_005f1);
    _jspx_th_admin_005fsubtitle_005f1.setJspContext(_jspx_page_context);
    // /trampoline/pick_lists/archive.jsp(169,0) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fsubtitle_005f1.setText("Key for Reels: On pick list / staged / checked OUT");
    _jspx_th_admin_005fsubtitle_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fsubtitle_005f1);
    return false;
  }

  private boolean _jspx_meth_admin_005fbox_005fbegin_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:box_begin
    org.apache.jsp.tag.webadmin.box_005fbegin_tag _jspx_th_admin_005fbox_005fbegin_005f1 = (new org.apache.jsp.tag.webadmin.box_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fbox_005fbegin_005f1);
    _jspx_th_admin_005fbox_005fbegin_005f1.setJspContext(_jspx_page_context);
    // /trampoline/pick_lists/archive.jsp(183,4) name = text type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fbox_005fbegin_005f1.setText("Key for Reels: On pick list / staged / checked OUT");
    // /trampoline/pick_lists/archive.jsp(183,4) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fbox_005fbegin_005f1.setName("results");
    _jspx_th_admin_005fbox_005fbegin_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fbox_005fbegin_005f1);
    return false;
  }

  private boolean _jspx_meth_listing_005fbegin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:begin
    org.apache.jsp.tag.weblisting.begin_tag _jspx_th_listing_005fbegin_005f0 = (new org.apache.jsp.tag.weblisting.begin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fbegin_005f0);
    _jspx_th_listing_005fbegin_005f0.setJspContext(_jspx_page_context);
    _jspx_th_listing_005fbegin_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fbegin_005f0);
    return false;
  }

  private boolean _jspx_meth_listing_005fheader_005fbegin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:header_begin
    org.apache.jsp.tag.weblisting.header_005fbegin_tag _jspx_th_listing_005fheader_005fbegin_005f0 = (new org.apache.jsp.tag.weblisting.header_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fheader_005fbegin_005f0);
    _jspx_th_listing_005fheader_005fbegin_005f0.setJspContext(_jspx_page_context);
    _jspx_th_listing_005fheader_005fbegin_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fheader_005fbegin_005f0);
    return false;
  }

  private boolean _jspx_meth_listing_005fheader_005fcell_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:header_cell
    org.apache.jsp.tag.weblisting.header_005fcell_tag _jspx_th_listing_005fheader_005fcell_005f0 = (new org.apache.jsp.tag.weblisting.header_005fcell_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fheader_005fcell_005f0);
    _jspx_th_listing_005fheader_005fcell_005f0.setJspContext(_jspx_page_context);
    // /trampoline/pick_lists/archive.jsp(187,12) name = width type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_listing_005fheader_005fcell_005f0.setWidth("75");
    // /trampoline/pick_lists/archive.jsp(187,12) name = first type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_listing_005fheader_005fcell_005f0.setFirst("true");
    // /trampoline/pick_lists/archive.jsp(187,12) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_listing_005fheader_005fcell_005f0.setName("Created");
    _jspx_th_listing_005fheader_005fcell_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fheader_005fcell_005f0);
    return false;
  }

  private boolean _jspx_meth_listing_005fheader_005fcell_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:header_cell
    org.apache.jsp.tag.weblisting.header_005fcell_tag _jspx_th_listing_005fheader_005fcell_005f1 = (new org.apache.jsp.tag.weblisting.header_005fcell_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fheader_005fcell_005f1);
    _jspx_th_listing_005fheader_005fcell_005f1.setJspContext(_jspx_page_context);
    // /trampoline/pick_lists/archive.jsp(188,12) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_listing_005fheader_005fcell_005f1.setName("Name");
    _jspx_th_listing_005fheader_005fcell_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fheader_005fcell_005f1);
    return false;
  }

  private boolean _jspx_meth_listing_005fheader_005fcell_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:header_cell
    org.apache.jsp.tag.weblisting.header_005fcell_tag _jspx_th_listing_005fheader_005fcell_005f2 = (new org.apache.jsp.tag.weblisting.header_005fcell_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fheader_005fcell_005f2);
    _jspx_th_listing_005fheader_005fcell_005f2.setJspContext(_jspx_page_context);
    // /trampoline/pick_lists/archive.jsp(189,12) name = width type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_listing_005fheader_005fcell_005f2.setWidth("150");
    // /trampoline/pick_lists/archive.jsp(189,12) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_listing_005fheader_005fcell_005f2.setName("Foreman");
    _jspx_th_listing_005fheader_005fcell_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fheader_005fcell_005f2);
    return false;
  }

  private boolean _jspx_meth_listing_005fheader_005fcell_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:header_cell
    org.apache.jsp.tag.weblisting.header_005fcell_tag _jspx_th_listing_005fheader_005fcell_005f3 = (new org.apache.jsp.tag.weblisting.header_005fcell_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fheader_005fcell_005f3);
    _jspx_th_listing_005fheader_005fcell_005f3.setJspContext(_jspx_page_context);
    // /trampoline/pick_lists/archive.jsp(190,12) name = width type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_listing_005fheader_005fcell_005f3.setWidth("50");
    // /trampoline/pick_lists/archive.jsp(190,12) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_listing_005fheader_005fcell_005f3.setName("Reels");
    _jspx_th_listing_005fheader_005fcell_005f3.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fheader_005fcell_005f3);
    return false;
  }

  private boolean _jspx_meth_listing_005fheader_005fcell_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:header_cell
    org.apache.jsp.tag.weblisting.header_005fcell_tag _jspx_th_listing_005fheader_005fcell_005f4 = (new org.apache.jsp.tag.weblisting.header_005fcell_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fheader_005fcell_005f4);
    _jspx_th_listing_005fheader_005fcell_005f4.setJspContext(_jspx_page_context);
    // /trampoline/pick_lists/archive.jsp(191,12) name = width type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_listing_005fheader_005fcell_005f4.setWidth("100");
    // /trampoline/pick_lists/archive.jsp(191,12) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_listing_005fheader_005fcell_005f4.setName("Status");
    _jspx_th_listing_005fheader_005fcell_005f4.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fheader_005fcell_005f4);
    return false;
  }

  private boolean _jspx_meth_listing_005fheader_005fcell_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:header_cell
    org.apache.jsp.tag.weblisting.header_005fcell_tag _jspx_th_listing_005fheader_005fcell_005f5 = (new org.apache.jsp.tag.weblisting.header_005fcell_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fheader_005fcell_005f5);
    _jspx_th_listing_005fheader_005fcell_005f5.setJspContext(_jspx_page_context);
    // /trampoline/pick_lists/archive.jsp(192,12) name = width type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_listing_005fheader_005fcell_005f5.setWidth("100");
    // /trampoline/pick_lists/archive.jsp(192,12) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_listing_005fheader_005fcell_005f5.setName("");
    _jspx_th_listing_005fheader_005fcell_005f5.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fheader_005fcell_005f5);
    return false;
  }

  private boolean _jspx_meth_listing_005fheader_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:header_end
    org.apache.jsp.tag.weblisting.header_005fend_tag _jspx_th_listing_005fheader_005fend_005f0 = (new org.apache.jsp.tag.weblisting.header_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fheader_005fend_005f0);
    _jspx_th_listing_005fheader_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_listing_005fheader_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fheader_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_listing_005fcell_005fbegin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:cell_begin
    org.apache.jsp.tag.weblisting.cell_005fbegin_tag _jspx_th_listing_005fcell_005fbegin_005f0 = (new org.apache.jsp.tag.weblisting.cell_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fcell_005fbegin_005f0);
    _jspx_th_listing_005fcell_005fbegin_005f0.setJspContext(_jspx_page_context);
    _jspx_th_listing_005fcell_005fbegin_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fcell_005fbegin_005f0);
    return false;
  }

  private boolean _jspx_meth_listing_005fcell_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:cell_end
    org.apache.jsp.tag.weblisting.cell_005fend_tag _jspx_th_listing_005fcell_005fend_005f0 = (new org.apache.jsp.tag.weblisting.cell_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fcell_005fend_005f0);
    _jspx_th_listing_005fcell_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_listing_005fcell_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fcell_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_listing_005fcell_005fbegin_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:cell_begin
    org.apache.jsp.tag.weblisting.cell_005fbegin_tag _jspx_th_listing_005fcell_005fbegin_005f1 = (new org.apache.jsp.tag.weblisting.cell_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fcell_005fbegin_005f1);
    _jspx_th_listing_005fcell_005fbegin_005f1.setJspContext(_jspx_page_context);
    _jspx_th_listing_005fcell_005fbegin_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fcell_005fbegin_005f1);
    return false;
  }

  private boolean _jspx_meth_listing_005fcell_005fend_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:cell_end
    org.apache.jsp.tag.weblisting.cell_005fend_tag _jspx_th_listing_005fcell_005fend_005f1 = (new org.apache.jsp.tag.weblisting.cell_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fcell_005fend_005f1);
    _jspx_th_listing_005fcell_005fend_005f1.setJspContext(_jspx_page_context);
    _jspx_th_listing_005fcell_005fend_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fcell_005fend_005f1);
    return false;
  }

  private boolean _jspx_meth_listing_005fcell_005fbegin_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:cell_begin
    org.apache.jsp.tag.weblisting.cell_005fbegin_tag _jspx_th_listing_005fcell_005fbegin_005f2 = (new org.apache.jsp.tag.weblisting.cell_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fcell_005fbegin_005f2);
    _jspx_th_listing_005fcell_005fbegin_005f2.setJspContext(_jspx_page_context);
    _jspx_th_listing_005fcell_005fbegin_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fcell_005fbegin_005f2);
    return false;
  }

  private boolean _jspx_meth_listing_005fcell_005fend_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:cell_end
    org.apache.jsp.tag.weblisting.cell_005fend_tag _jspx_th_listing_005fcell_005fend_005f2 = (new org.apache.jsp.tag.weblisting.cell_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fcell_005fend_005f2);
    _jspx_th_listing_005fcell_005fend_005f2.setJspContext(_jspx_page_context);
    _jspx_th_listing_005fcell_005fend_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fcell_005fend_005f2);
    return false;
  }

  private boolean _jspx_meth_listing_005fcell_005fbegin_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:cell_begin
    org.apache.jsp.tag.weblisting.cell_005fbegin_tag _jspx_th_listing_005fcell_005fbegin_005f3 = (new org.apache.jsp.tag.weblisting.cell_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fcell_005fbegin_005f3);
    _jspx_th_listing_005fcell_005fbegin_005f3.setJspContext(_jspx_page_context);
    _jspx_th_listing_005fcell_005fbegin_005f3.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fcell_005fbegin_005f3);
    return false;
  }

  private boolean _jspx_meth_listing_005fcell_005fend_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:cell_end
    org.apache.jsp.tag.weblisting.cell_005fend_tag _jspx_th_listing_005fcell_005fend_005f3 = (new org.apache.jsp.tag.weblisting.cell_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fcell_005fend_005f3);
    _jspx_th_listing_005fcell_005fend_005f3.setJspContext(_jspx_page_context);
    _jspx_th_listing_005fcell_005fend_005f3.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fcell_005fend_005f3);
    return false;
  }

  private boolean _jspx_meth_listing_005fcell_005fbegin_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:cell_begin
    org.apache.jsp.tag.weblisting.cell_005fbegin_tag _jspx_th_listing_005fcell_005fbegin_005f4 = (new org.apache.jsp.tag.weblisting.cell_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fcell_005fbegin_005f4);
    _jspx_th_listing_005fcell_005fbegin_005f4.setJspContext(_jspx_page_context);
    _jspx_th_listing_005fcell_005fbegin_005f4.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fcell_005fbegin_005f4);
    return false;
  }

  private boolean _jspx_meth_listing_005fcell_005fend_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:cell_end
    org.apache.jsp.tag.weblisting.cell_005fend_tag _jspx_th_listing_005fcell_005fend_005f4 = (new org.apache.jsp.tag.weblisting.cell_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fcell_005fend_005f4);
    _jspx_th_listing_005fcell_005fend_005f4.setJspContext(_jspx_page_context);
    _jspx_th_listing_005fcell_005fend_005f4.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fcell_005fend_005f4);
    return false;
  }

  private boolean _jspx_meth_listing_005fcell_005fbegin_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:cell_begin
    org.apache.jsp.tag.weblisting.cell_005fbegin_tag _jspx_th_listing_005fcell_005fbegin_005f5 = (new org.apache.jsp.tag.weblisting.cell_005fbegin_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fcell_005fbegin_005f5);
    _jspx_th_listing_005fcell_005fbegin_005f5.setJspContext(_jspx_page_context);
    // /trampoline/pick_lists/archive.jsp(227,12) name = align type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_listing_005fcell_005fbegin_005f5.setAlign("right");
    _jspx_th_listing_005fcell_005fbegin_005f5.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fcell_005fbegin_005f5);
    return false;
  }

  private boolean _jspx_meth_listing_005fcell_005fend_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:cell_end
    org.apache.jsp.tag.weblisting.cell_005fend_tag _jspx_th_listing_005fcell_005fend_005f5 = (new org.apache.jsp.tag.weblisting.cell_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fcell_005fend_005f5);
    _jspx_th_listing_005fcell_005fend_005f5.setJspContext(_jspx_page_context);
    _jspx_th_listing_005fcell_005fend_005f5.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fcell_005fend_005f5);
    return false;
  }

  private boolean _jspx_meth_listing_005frow_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:row_end
    org.apache.jsp.tag.weblisting.row_005fend_tag _jspx_th_listing_005frow_005fend_005f0 = (new org.apache.jsp.tag.weblisting.row_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005frow_005fend_005f0);
    _jspx_th_listing_005frow_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_listing_005frow_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005frow_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_listing_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  listing:end
    org.apache.jsp.tag.weblisting.end_tag _jspx_th_listing_005fend_005f0 = (new org.apache.jsp.tag.weblisting.end_tag());
    _jsp_instancemanager.newInstance(_jspx_th_listing_005fend_005f0);
    _jspx_th_listing_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_listing_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_listing_005fend_005f0);
    return false;
  }

  private boolean _jspx_meth_admin_005fbox_005fend_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:box_end
    org.apache.jsp.tag.webadmin.box_005fend_tag _jspx_th_admin_005fbox_005fend_005f1 = (new org.apache.jsp.tag.webadmin.box_005fend_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fbox_005fend_005f1);
    _jspx_th_admin_005fbox_005fend_005f1.setJspContext(_jspx_page_context);
    _jspx_th_admin_005fbox_005fend_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fbox_005fend_005f1);
    return false;
  }

  private boolean _jspx_meth_admin_005fsubtitle_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:subtitle
    org.apache.jsp.tag.webadmin.subtitle_tag _jspx_th_admin_005fsubtitle_005f2 = (new org.apache.jsp.tag.webadmin.subtitle_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fsubtitle_005f2);
    _jspx_th_admin_005fsubtitle_005f2.setJspContext(_jspx_page_context);
    // /trampoline/pick_lists/archive.jsp(243,4) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fsubtitle_005f2.setText("No Pick Lists Found.");
    _jspx_th_admin_005fsubtitle_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fsubtitle_005f2);
    return false;
  }

  private boolean _jspx_meth_admin_005fset_005ftabset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  admin:set_tabset
    org.apache.jsp.tag.webadmin.set_005ftabset_tag _jspx_th_admin_005fset_005ftabset_005f0 = (new org.apache.jsp.tag.webadmin.set_005ftabset_tag());
    _jsp_instancemanager.newInstance(_jspx_th_admin_005fset_005ftabset_005f0);
    _jspx_th_admin_005fset_005ftabset_005f0.setJspContext(_jspx_page_context);
    // /trampoline/pick_lists/archive.jsp(247,0) name = url type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fset_005ftabset_005f0.setUrl("pick_lists/_tabset_default.jsp");
    // /trampoline/pick_lists/archive.jsp(247,0) name = thispage type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_admin_005fset_005ftabset_005f0.setThispage("archive.jsp");
    _jspx_th_admin_005fset_005ftabset_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_admin_005fset_005ftabset_005f0);
    return false;
  }

  private boolean _jspx_meth_html_005fend_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:end
    org.apache.jsp.tag.webhtml.end_tag _jspx_th_html_005fend_005f0 = (new org.apache.jsp.tag.webhtml.end_tag());
    _jsp_instancemanager.newInstance(_jspx_th_html_005fend_005f0);
    _jspx_th_html_005fend_005f0.setJspContext(_jspx_page_context);
    _jspx_th_html_005fend_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_html_005fend_005f0);
    return false;
  }
}
